### ISSUE TITLE
Modern CMake usage

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#103]
Currently, the `Find*.cmake` modules for Corrade and Magnum projects are done the "old" way, with all the ugly stuff like under-the hood global compiler flag modifications, long incomprehensible names for variables which specify libraries, include dirs, dependencies etc. As taken from current `base` branch of Magnum Bootstrap repo:
```cmake
cmake_minimum_required(2.8.9)
project(MyApplication)

find_package(Magnum REQUIRED
    Sdl2Application)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CORRADE_CXX_FLAGS}")
include_directories(${MAGNUM_INCLUDE_DIRS} ${MAGNUM_APPLICATION_INCLUDE_DIRS})

add_executable(MyApplication MyApplication.cpp)
target_link_libraries(MyApplication
    ${MAGNUM_APPLICATION_LIBRARIES}
    ${MAGNUM_LIBRARIES})
```

With the modern way, the same could be done more-or-less this way:
```cmake
cmake_minimum_required(3.0.0)
project(MyApplication CXX)

find_package(Magnum REQUIRED
    Sdl2Application)

add_executable(MyApplication MyApplication.cpp)
target_link_libraries(MyApplication
    Magnum::Magnum
    Magnum::Application)
```

Specifying just `target_link_libraries(MyApplication Magnum::<something>)` will do all these things:

- add all required include paths, even for dependencies
- set up compiler flags, if needed (`-std=c++11` for GCC/Clang)
- link all required libraries and dependency libraries
- set up additional options based on user-specified target properties

The main advantage is that it is shorter, less error-prone than variables and allows the `Find*.cmake` file to be radically simpler.

Stuff that needs to be sorted out:

- [x] Minimal CMake version will be 2.8.12. ~~Can we afford that already? Last I checked, the oldest version on OpenEmbedded Linux is only 2.8.11, Ubuntu 14.04 has 2.8.12.~~ 2.8.12 is a crucial release with many new features and keeping compatibility with older versions would make it a maintenance hell.
- [x] Header-only libraries (such as `Corrade::Containers`) need support for `INTERFACE` libraries, which are in 3.0 ~~(fortunately almost everybody would use that just as a dependency of something else so that's not much a problem)~~ -- `Corrade::Containers` are available only if you have CMake 3.0+
- [x] Portable way to override compiler standard (`C_STANDARD` property) is in 3.1, need to find a way how to specify minimal one and allow the user to change it to something else, need to find a way how to do it on <3.1
- [x] Easy way for the user to add optional `${CORRADE_CXX_FLAGS}` (special property and generator expression that adds it?)
- [x] ~~Backward compatible so it's still possible to use the old `${MAGNUM_*_LIBRARIES}` way (is `set(MAGNUM_SOMETHING_LIBRARIES Magnum::Something)` too ugly? we probably need to have the variables for creating the imported targets anyway)~~ Done exactly that way, seems to work.
- [x] ~~Backward compatible for users with old versions -- I fear that the generator expressions would be poorly supported~~ Not an issue.
- [x] ~~It is not possible to call `target_link_libraries()` on `OBJECT` libraries to add include dirs, set up compiler flags etc. (only an ugly workaround). Related bug: https://public.kitware.com/Bug/view.php?id=14778~~ Ugly and painful but that's just internal code, fortunately.

If CMake >2.8.9 can be used as minimal, we can make use of these new features:

- [x] ~~`CMAKE_LANG_VISIBILITY_PRESET` instead of manual `-fvisibility=hidden` (since 2.8.12)~~ Always enabled, no need to expose it to the user.
- [ ] Reduce `project()` calls to use just `CXX` and not `C` (since 3.0, I think, 2.8.12 has a bug in compiler detection code)
- [ ] [CMAKE_CONFIGURE_DEPENDS](https://cmake.org/cmake/help/latest/prop_dir/CMAKE_CONFIGURE_DEPENDS.html#prop_dir:CMAKE_CONFIGURE_DEPENDS) instead of a hack with `configure_file()` to trigger CMake re-run (since 3.0)
- [ ] [IOS_INSTALL_COMBINED](https://cmake.org/cmake/help/latest/prop_tgt/IOS_INSTALL_COMBINED.html#prop_tgt:IOS_INSTALL_COMBINED) (since 3.5)

**Comment by LB--** [comment]
It would also be nice to have optional [Biicode](https://www.biicode.com/) support in the future. The layout of this library and its many optional components are kind of awkward in Biicode, but they were able to port Boost so it should definitely be possible. If/when Magnum starts using modern CMake I'd be happy to work on the Biicode support myself. Biicode requires CMake 3.0.2 or above, but it can be integrated into existing CMake projects in an optional manner.

> Portable way to override compiler standard (`C_STANDARD` property) is in 3.1, need to find a way how to specify minimal one and allow the user to change it to something else

From the documentation, `CXX_STANDARD_REQUIRED` is just a boolean flag indicating whether `CXX_STANDARD` can decay to an older version. Since both properties have a `CMAKE_*` variant that the user can specify on the command line, it should be safe to just detect whether the property is already set or not, thus allowing the user to specify a more recent version if they want.

Alternatively, there is now support for detecting and requesting compile features, so instead of requesting a specific language standard you could instead just request all the language/compiler features you need. This can also be used to make some features optional.

---
Also, I am curious about your reasoning for wanting to support very old versions of CMake - I know some platforms don't have newer versions available by default, but Magnum requires pretty decent compilers anyway and building a more recent version of CMake from source is really easy to do (unless there are complications on particular platforms I am not aware of?). I guess the tradeoff is between requiring users to upgrade their CMake and being able to use newer features that make using the library easier?

**Comment by mosra** [comment]
Biicode -- sure, heard about it, but didn't get a chance to play with it yet (thus I don't even know how much I have to change/update to be compatible with it).

Supporting old versions -- sadly it's not just a matter of "hey, user, upgrade your package". There is the already mentioned Ubuntu LTS, which will be here for at least one more year, and which is a distribution of choice for *many* people/companies -- I don't want to mark this distribution as unsupported just because it has just one outdated package and I don't want to force the users *by default* to install some questionable PPAs to upgrade from 2.8.12 to >= 3.0. That would make the adoption curve even steeper.

But more importantly there are embedded systems that just can't easily update the package without breaking everything else (I'm having just one like that at work, with CMake 2.8.11).

So I guess the way to go, currently, is to conditionally enable the new features only for recent versions of CMake.

**Comment by LB--** [comment]
Ok, I understand.

**Comment by LB--** [comment]
I was unaware, but apparently biicode is dead: http://blog.biicode.com/biicode-just-the-company-post-mortem/  
The forums aren't even functioning anymore. It seems a lot of people have abandoned it because of the grim prospect, even if the main site is still functional. Maybe it isn't worth the effort to support biicode if it isn't very popular and is dying. To be honest I never really was happy with how biicode worked, I only recommended it because I didn't know of any alternatives...until now.

I recently discovered two other C/C++ dependency managers, and unlike biicode they are written purely in CMake and don't require installation of additional software or massive changes in project layout:
* [hunter](https://github.com/ruslo/hunter) - currently actively maintained, I found out because the author posted to the CMake mailing lists
* [https://github.com/iauns/cpm](cpm) - looks to be very similar but the copypasta is pretty ugly and it hasn't been updated in nearly a year

I haven't used either one yet, I just wanted to point out the biicode death and that there are other alternatives to consider.

**Comment by mosra** [comment]
Huh. I saw a "remove biicode support" commit in some project some time ago and was really wondering why is that and what was going on.

Hunter looks .. actually very interesting, hmm!

**Comment by smspillaz** [comment]
There is also https://www.conan.io. I believe this is effectively a rewritten version of biicode. I was going to port my projects to it some time in the future when I get the time to (currently they're all on biicode).

**Comment by mosra** [comment]
I'm now working on a "Modern CMake" rework of all repos (so usage like in the snippet above), targeting CMake 2.8.12. The code is currently in `cmake-ng` branches of Corrade and Magnum repositories (along with updated documentation), more repos to come. It should be largely backwards compatible, but some issues with advanced features like OBJECT libraries may happen. I'm still not very happy with the way how C++11 is enabled in the compiler and how the pedantic flags are passed, so that still needs a bit more work.

If anyone is willing to be an "early adopter" and test the changes, I'll be more than happy! :)

**Comment by mosra** [comment]
After much pain and anger, I was able to get much better behavior for setting C++ standard mode, I think even better than what's now achievable with CMake builtin `CXX_STANDARD` property. Similar to the `CXX_STANDARD` it allows you to specify what standard do you want to use, but also what standard should the users of the library use and then the highest from all will be used. Example:

```cmake
add_executable(exe1 ...) # uses C++03 (the default)

add_executable(exe2 ...) # uses C++11
set_target_properties(exe2 CORRADE_CXX_STANDARD 11)

add_executable(exe3 ...) # uses C++11 because Corrade::Utility requires it
target_link_libraries(exe3 Corrade::Utility)

add_library(lib1 ...) # users of this library need to use C++14
set_target_properties(lib1 PROPERTIES INTERFACE_CORRADE_CXX_STANDARD 14)

add_executable(exe4 ...) # uses C++14 because it's the highest requirement of all libs
target_link_libraries(exe4 Corrade::Utility lib1)
```

It is also possible to set default standard for whole directory:
```cmake
set_directory_properties(PROPERTIES CORRADE_CXX_STANDARD 14)

add_executable(exe5 ...) # uses C++14

add_executable(exe6 ...) # uses C++11
set_target_properties(exe6 PROPERTIES CORRADE_CXX_STANDARD 11)
```

Works on CMake >= 3.0, CMake 2.8.12 has a stripped-down version of this because it lacks some needed features.

**Comment by mosra** [comment]
Done in 01ffbe93a95c3f2e5dcac561f621be3778a60cb5 and surrounding commits, similarly in other projects. Tested backwards compatibility, but of course something can always go wrong, so please bug me if you find something wrong.

Glad for having this finally sorted out.

**Comment by Squareys** [comment]
Awesome!
