### ISSUE TITLE
Text input for Sdl2Application

### ISSUE THREAD

**Issue by jaynus** [mosra/magnum#129]
I am currently implementing some straight text windows in my project, and realized the Magnum key events are currently insufficient in the SDL2PlatformApplication for handling the actual text code of the keyboard event. 

This is needed for receiving actual character codes of keys of the host system, and not deducing keyboard types yourselves (e.g. SHIFT+9 = ')' and such).

These are passed via SDL_TEXTEVENT in the main loop which provide the actual OS key value which supposedly was pressed, after a given KEYPRESS event. I have implemented a solution in my project, however, I'd like to push it upstream to you. I was uncertain on what you would prefer for the implementation prior to a PR though. 

1. I have implemented it as a char text() const; member in the KeyEvent class. The actual 'text' value from the event is statefully tracked, and provided within the KeyEvent class to keyPress/keyRelease

2. If you do not prefer the above, this could also be implemented as its own type of Key(Text?)Event.

Please advise, so I can either submit a PR or rewrite to your preference :)

**Comment by mosra** [comment]
Hey, awesome, I was just thinking about this a few days ago (I need this feature too, but for iOS with on-screen keyboard and such). However, I'd like it to be properly Unicode-aware, so I guess just `char text()` is not enough. Also I don't exactly know how just that function would handle backspace/delete, cursor keys etc. (I assume SDL handles that?)

My idea was to mirror the SDL API with `startTextInput(Range2D rect)`, `endTextInput()` and a new `TextEditingEvent`/`TextInputEvent` event class. Possibly some convenience wrapper around that so the user doesn't have to juggle with pointers.

I'm not sure about how the SDL API works for editing already present text, because I see no way how to enter the text for editing etc. I guess we'll have to try.

**Comment by jaynus** [comment]
Yah your right, the SDL version are unicode aware - mine is not. The SDL version provides a full 32-bytes for the possible character test provided (via SDL_TEXTEVENT.text). I'm currently just pulling the UTF-8 variant from SDL_TEXTEVENT.state. I don't think much work would be needed to transition to unicode and mirror it; just unicode support for these events heavily changed in SDL2, its hard to find proper docs on it.

You can see what I'm using (for now) here - 30b01828bf93a0ed9b583e29697928c18a07d62e

I'll continue fleshing it out for unicode to confirm it works. It looks like the best design path (and the one I already took) is as you said, so I'll move that direction :)

Looks like we'll get textEvent/textEditingEvent and support those events appropriately. I'll rename keyTextEvent to textEvent, and flesh out the unicode support instead of the bastardized-sorta-UTF-8 I have going on now :P

**Comment by mosra** [comment]
Awesome, looking forward to this! :+1:

**Comment by mosra** [comment]
Implemented in 1398ffd24c8e684ac9c464c26bdf86cbb8cc76e2.

Note that this might be *way* more low-level than you think -- it just throws UTF-8 text sequences at you, and you are still responsible to handle everything else like cursor keys, backspace/delete etc. Still a lot of work.
