### ISSUE TITLE
Problem with configuring CMake

### ISSUE THREAD

**Issue by Crisspl** [mosra/magnum#130]
I`m just getting "Configuring incomplete, errors occurred!". No concrete errors, just nope. I'm trying to configure it for MinGW and I'm receiving this CMakeErrorLog file:

```
Determining if the system is big endian passed with the following output:
Change Dir: C:/Users/Crisser/Desktop/magnum-build/CMakeFiles/CMakeTmp

Run Build Command:"C:/PROGRA~2/CODEBL~1/MinGW/bin/mingw32-make.exe" "cmTC_08a55/fast"
C:/PROGRA~2/CODEBL~1/MinGW/bin/mingw32-make.exe -f CMakeFiles\cmTC_08a55.dir\build.make CMakeFiles/cmTC_08a55.dir/build

mingw32-make.exe[1]: Entering directory 'C:/Users/Crisser/Desktop/magnum-build/CMakeFiles/CMakeTmp'

Building C object CMakeFiles/cmTC_08a55.dir/TestEndianess.c.obj

C:\PROGRA~2\CODEBL~1\MinGW\bin\gcc.exe     -o CMakeFiles\cmTC_08a55.dir\TestEndianess.c.obj   -c C:\Users\Crisser\Desktop\magnum-build\CMakeFiles\CMakeTmp\TestEndianess.c

Linking C executable cmTC_08a55.exe

"C:\Program Files (x86)\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\cmTC_08a55.dir\link.txt --verbose=1

"C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f CMakeFiles\cmTC_08a55.dir/objects.a

C:\PROGRA~2\CODEBL~1\MinGW\bin\ar.exe cr CMakeFiles\cmTC_08a55.dir/objects.a @CMakeFiles\cmTC_08a55.dir\objects1.rsp

C:\PROGRA~2\CODEBL~1\MinGW\bin\gcc.exe       -Wl,--whole-archive CMakeFiles\cmTC_08a55.dir/objects.a -Wl,--no-whole-archive  -o cmTC_08a55.exe -Wl,--out-implib,libcmTC_08a55.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\cmTC_08a55.dir\linklibs.rsp

mingw32-make.exe[1]: Leaving directory 'C:/Users/Crisser/Desktop/magnum-build/CMakeFiles/CMakeTmp'


TestEndianess.c:
/* A 16 bit integer is required. */
typedef unsigned short cmakeint16;

/* On a little endian machine, these 16bit ints will give "THIS IS LITTLE ENDIAN."
   On a big endian machine the characters will be exchanged pairwise. */
const cmakeint16 info_little[] =  {0x4854, 0x5349, 0x4920, 0x2053, 0x494c, 0x5454, 0x454c, 0x4520, 0x444e, 0x4149, 0x2e4e, 0x0000};

/* on a big endian machine, these 16bit ints will give "THIS IS BIG ENDIAN."
   On a little endian machine the characters will be exchanged pairwise. */
const cmakeint16 info_big[] =     {0x5448, 0x4953, 0x2049, 0x5320, 0x4249, 0x4720, 0x454e, 0x4449, 0x414e, 0x2e2e, 0x0000};

#ifdef __CLASSIC_C__
int main(argc, argv) int argc; char *argv[];
#else
int main(int argc, char *argv[])
#endif
{
  int require = 0;
  require += info_little[argc];
  require += info_big[argc];
  (void)argv;
  return require;
}
```
Is it part of CMake code? What's happening? I've done everything how explained in your getting started tutorial.

**Comment by mosra** [comment]
Hmm. The output you posted is just *very* verbose log of CMake's internal endian checking code, which it says that it passed, so the error must be somewhere else. I just checked with my local CI and latest master branch of both Corrade and Magnum and didn't encounter any problem with MinGW builds (but on Linux, not Windows).

Can you paste the whole command-line output? What is your CMake version?

**Comment by LB--** [comment]
> I just checked [...] (but on Linux, not Windows).

I checked on WIndows and everything is fine for me.

**Comment by mosra** [comment]
@LB-- thank you!

I hope this is not related to building all the repositories in one go as [explained here](http://mosra.cz/blog/magnum-doc/getting-started.html). In my tests I'm building everything separately.

**Comment by Crisspl** [comment]
I was using exactly this instructions. I don't know if this counts (especially on the step of just configuring CMake), but my MinGW is 32bit version attached to Code::Blocks (GCC 4.8.1) - codeblocks-13.12mingw-setup-TDM-GCC-481.exe download option.
CMakeOutput below:
[CMakeOutput.txt](https://github.com/mosra/magnum/files/93545/CMakeOutput.txt)

**Comment by LB--** [comment]
I'm also using CMake 3.4.1, I just tried the subdirectory build process on Windows with a 4-line CMake file like this:
```cmake
cmake_minimum_required(VERSION 3.4)
project(Magnum-sub-build)
add_subdirectory(corrade)
add_subdirectory(magnum)
```
It works fine for me, though I did notice that I had to disable my existing Corrade installation because it favors that over the subdirectory Corrade.

**Comment by mosra** [comment]
The output is completely okay with no error message, I really wonder where's the problem. I'm interested in the user-visible output produced by CMake, which should look kinda like this:

```
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works

...

-- Using unsigned short
-- Check if the system is big endian - little endian
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mosra/Code/corrade/build
```

I've never used Code::Blocks, so I don't know whether this output is even shown to the user.

**Comment by Crisspl** [comment]
@LB-- - I don't know if you meant this but I just replaced my CMakeLists file with yours but nothing changed :/ I don't know anything about CMake commands (?) so i can't make up anything...

@mosra I use gui and this time... I don't see any output while configuring, just after a second there show this error.
But... I just found there is one more concrete information, but it wasn't visible, I had to scroll up ( I use gui). So, ekhm, sorry...

```
Could NOT find SDL2 (missing:  SDL2_LIBRARY SDL2_INCLUDE_DIR) 
CMake Error at magnum/src/Magnum/Platform/CMakeLists.txt:127 (message):
  SDL2 library, required by Sdl2Application, was not found.  Set
  WITH_SDL2APPLICATION to OFF to skip building it.
```
Should I give it a path to SDL? But it shouldn't be already in source code? :|
After getting the error there shows 2 more CMake vars: SDL2_INCLUDE_DIR with value SDL2_INCLUDE_DIR-NOTFOUND and SDL2_LIBRARY with value SDL2_LIBRARY-NOTFOUND.

**Comment by mosra** [comment]
Ahh, great, I was afraid that something very fishy was going on :)

Yes, you need to provide SDL2. Download the development libraries from http://libsdl.org/download-2.0.php, direct `SDL2_INCLUDE_DIR` to its `include/` dir and `SDL2_LIBRARY` to the library.

**Comment by Crisspl** [comment]
Ok, it configured and generated correctly :) Thanks very much.
Also compiled it but there were few little problems:
I had to change #include in corrade...\Utility\Directory.cpp from wtypesbase.h to wtypes.h. Seems that my compiler has diiferent name for this file...
And I had to use *.lib from x86 directory, when linked lib from x64 I got some undefined references.

And so... I compiled and... Maybe I'm idiot, but how I'm supposed  to use it? It's just an exe file showing dark-grey window and some informations in console (btw I'm a bit worried that it claims "OpenGL version: 2.1.2", I'm on GTX660).

**Comment by mosra** [comment]
Awesome! :)

> I had to use *.lib from x86 directory, when linked lib from x64 I got some undefined references.

I guess that's because you are using 32bit MinGW?

> I had to change #include in corrade...\Utility\Directory.cpp from wtypesbase.h to wtypes.h

Fixed in mosra/corrade@645fa5b928b3a21e0aaa6ccde1dd3fed532cd438. This was some workaround for I don't know what, so maybe things changed since. Thanks!

> It's just an exe file showing dark-grey window and some informations in console

Yes, that's it. :) A *minimal* application to get you started. It means that it's the least amount of code needed to display a window, nothing more, making it simple to understand. At the bottom of [Getting Started Guide](http://mosra.cz/blog/magnum-doc/getting-started.html#getting-started-build) there are some hints about what you can add to achieve something more than a grey window and also links to tutorials and examples. Have fun!

> I'm a bit worried that it claims "OpenGL version: 2.1.2", I'm on GTX660

That's weird. Does it really say that the renderer is NVidia? Do you have up-to-date NV drivers? Is it possible that you have NVidia Optimus and an integrated Intel card got used instead? Current NV driver version is something like 358.16 or maybe even higher.

**Comment by Crisspl** [comment]
Ah, ok, I already undestand. At first look I expected a lib that I can link to my project, but this time it works differently. Ok, it's new for me :D A bit weird that I have to compile whole engine, at least for me.

Yes, it correctly shows GTX 660. I don't have the newest drivers (exactly 320.18 - in fact quite old), but I use OpenGL 3.3 in my another little project and... it's working.

**Comment by mosra** [comment]
Yes, of course it can be a lib that you link into your project, you can also [use whatever windowing system you want](http://mosra.cz/blog/magnum-doc/platform.html#platform-custom) and it also doesn't need to be "whole engine" -- open CMake GUI, point it to the build directory and untick all `WITH_` tickboxes that you don't find useful for your project. The core libraries are actually pretty small.

If it is working elsewhere, it should be working here too (in fact it would be a problem of SDL2, not of this engine), although I'm not really sure about these kinda older drivers. Can you try running the "grey box" application like this to see if it makes a difference?

```
./MyApplication --magnum-disable-workarounds "amd-nv-no-forward-compatible-core-context"
```

**Comment by Crisspl** [comment]
Yes, it makes a difference. Now it shows 3.1.0.

**Comment by Crisspl** [comment]
Yes, it makes a difference. With this option it shows version 3.1. 

I unticked WITH_SDL2APPLICATION but it's still looking for SDL (i think so..).
```
Could NOT find SDL2 (missing:  SDL2_LIBRARY SDL2_INCLUDE_DIR) 
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Magnum (missing: Sdl2Application)
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  modules/FindMagnum.cmake:595 (find_package_handle_standard_args)
  src/CMakeLists.txt:1 (find_package)
```
With WITH_SDL2APPLICATION set to false it should make a project to compile as a linkable lib?
I'm sorry for my endless questions. As you see, I'm completely new in it. I really appreciate your help.

**Comment by LB--** [comment]
It is still looking for SDL2 because of this line in the boostrap projecttemlate you are using:
```cmake
find_package(Magnum REQUIRED
    Sdl2Application)
```
You can use Magnum without SDL2, but if you want to draw graphics you need at least one library and SDL2 is one such library. Otherwise you can use Magnum as just a math library and not deal with graphics, but I don't think that's what you want.

>  it should make a project to compile as a linkable lib?

You can build the magnum libraries to store on your system and link to later in other projects, but you will always have to use CMake. Magnum isn't a mini library that you can just grab a .dll and .h and link to it - it's more complicated than that.

The bootstrap project is a template for starting a new project using Magnum - if you already have existing code, I recommend incorporating it into the bootstrap template - it will be easier.

**Comment by Crisspl** [comment]
"You can use Magnum without SDL2, but if you want to draw graphics you need at least one windowing system and SDL2 is one such library."

Yes, I'm not such a newbie :D What I wanted is to have *.lib which I can link to project, *.dll and includes directory as I was always meeting with. Windowed system (something that is able to create window) would be also linked like everything else.

Yes, I know I'm supposed to use CMake every time. If I need SDL also to compile as those libraries you mentioned, just tell me how to do that.

**Comment by mosra** [comment]
Just to clarify: you can clone the Magnum and Corrade repositories *without* integrating it into the bootstrap project. You can compile and install them separately, that's the standard way to do it and is explained in the thorough building docs [for Corrade](http://mosra.cz/blog/corrade-doc/building-corrade.html) and [for Magnum](http://mosra.cz/blog/magnum-doc/building.html). Then you get the includes and libraries somewhere on your system and you can [search for them using CMake](http://mosra.cz/blog/magnum-doc/cmake.html).

I mean, because people complained that they "got just some library files" and "there is no project to start on" and "too many separate things" (as you can imagine, it's impossible to please everyone :D), I made the Getting Started Guide so it builds both the libraries and the sample application in one big pile. That makes it easier for users to evaluate, but it doesn't make the relibraries usable elsewhere and is not efficient to work with in the long run.

> Yes, it makes a difference. With this option it shows version 3.1.

Hmm. So at least the workaround of a workaround works :) Would it be possible for you to update the drivers to latest and try again without any parameter? You should be able to get OpenGL 4.5, I really don't know what is happening in those old drivers, never had such issue with current versions.

**Comment by Crisspl** [comment]
Hm.. yea, I can imagine... but I wouldn't expect anyone to want to have start project. Whatever.

So... I compiled Corrade and I got 4 libs and 4 dlls. But with Magnum there's a problem at the moment of configuring in CMake... I gave it all paths (CORRADE_INLUDE_DIR - src\Corrade in result directory of Corrade, corrade-rc.exe I found somewhere with built libs, _CORRADE_CONFIGURE_FILE - configure.h in root result Corrade dir? and modules directory in result Corrade dir). But it's complaining about missing libraries (utility, interconnect etc.), but there's not even var to give it a path to it. Probably I gave it wrong directory, but there's nowhere precised what var is for exactly what.

**Comment by LB--** [comment]
Where did you install Corrade to? What path did you set `CMAKE_INSTALL_PREFIX` to? If you set the same for Magnum, it will find everything for you.

**Comment by Crisspl** [comment]
Ah, I just didn't know what CMAKE_INSTALL_PREFIX for. Now i got it.
Now compilation... where resulting Magnum project searches for Corrade includes? I put Corrade dir (the dir with all the includes) to the same directory as libs. But it can't find it.

**Comment by mosra** [comment]
Great! :) .. and @LB-- thank you a lot for your help!

> What is libMagnum .dll and .a for if there are many minor libs?

The main library contains root Magnum namespace, which contains the OpenGL abstraction layer, and also Math (for, ahem, math stuff) and Trade namespace (for data import/export). That's what you get if you disable everything else.

**Comment by Crisspl** [comment]
Ok, I'm trying to compile a single simple project with those libs linked. I get undefined references to glGetString and isDriverWorkaroundDisabled functions. The second one is probably in one of Magnum libs, but glGetString? What should I link? Also I'd be grateful for info which lib contains the second one.

```
undefined reference to `_imp__glGetString@4'|
undefined reference to `_imp___ZN6Magnum7Context26isDriverWorkaroundDisabledERKSs'|

```

**Comment by nabijaczleweli** [comment]
@Crisspl for `glGetString()` you should link to `GL` on Linux and `opengl32` on Windows (as in `-lGL`/`-lopengl32`)

**Comment by Crisspl** [comment]
O, thanks, I found it on Google. One more Magnum undefined reference error appeared, I'll just try to link all the libs and find which contains required functions ;_;

**Comment by mosra** [comment]
Hum. Linking to `${MAGNUM_LIBRARIES}` should resolve both errors (and you don't need to link to `opengl32` then). Try reordering the list of linked libraries, it sometimes helps too.

**Comment by Crisspl** [comment]
What is ${MAGNUM_LIBRARIES} ? A CMake var? I'm linking classically through Code::Blocks project.
Reordering doesb't seem to make any difference.

**Comment by nabijaczleweli** [comment]
ha ha ha rip
Use CMake, please

**Comment by LB--** [comment]
You need to use CMake to generate your project. CMake can generate a Code::Blocks project for you.

**Comment by mosra** [comment]
It is possible to *not* use CMake, but then you are completely on your own and you have to figure out everything from scratch. I decided to maintain only CMake project files, because otherwise I would need to maintain Unix Makefiles, MinGW makefiles, Ninja buildfiles, VS2012 project files, VS2015 project files, Windows Phone project files, Windows Store project files, Eclipse project files, XCode project files for OSX, XCode project files for iOS, KDevelop project files, Kate project files, Sublime Text project files, Code::Blocks project files, QtCreator project files, Android Studio projects, something completely different for Emscripten and NaCl and many more to suit everyone's taste. CMake is able to generate most of these. Yes, it is painful to use, but there is nothing like that with such multiplatform support and feature set.

**Comment by Crisspl** [comment]
I got stucked in one moment. CMake just won't find Corrade's configure.h. I gave a direct path to the file to _CORRADE_CONFIGURE_FILE, but nothing. In error I see it is searching in correct dir. Weird is that, whatever I put into _CORRADE_CONFIGURE_FILE (by Add Entry because it's not visible, the name of var i got from FindCorrade.cmake) it searches in always the same dir, but it's correct one so...
Full error:
```
CMake Error at modules/FindCorrade.cmake:206 (file):
  file failed to open for reading (No such file or directory):

    C:/Program Files (x86)/CodeBlocks/MinGW/Corrade/include/Corrade/include/Corrade/configure.h
Call Stack (most recent call first):
  modules/FindMagnum.cmake:154 (find_package)
  CMakeLists.txt:4 (find_package)
```

**Comment by Crisspl** [comment]
Probably I did it, but I'm not sure. The project just won't run. It claims that it's not built yet every time and I get "Process terminated with status 0" without even showing cmd window. It also seems not to even check error in code. I can miss semicolon or bracket and everything looks like described above...

**Comment by Crisspl** [comment]
Ok, I have absolutely no knowledge about CMake commands, but I more-less copied CMakeLists file from one of examples and it actually works! So... thanks and sorry for annoying questions.

**Comment by mosra** [comment]
Great to hear that :)

Closing this as solved, in case you have more questions, please stop by at https://gitter.im/mosra/magnum (or send me an e-mail or whatever else).
