### ISSUE TITLE
No way to specify GL_PATCH_VERTICES

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum#164]
Hi everybody!

There seems to be no way to specify `GL_PATCH_VERTICES` as in (https://www.opengl.org/registry/specs/ARB/tessellation_shader.txt):

```
    void PatchParameteri(enum pname, int value);

    Accepted by the <pname> parameter of PatchParameteri, GetBooleanv,
    GetDoublev, GetFloatv, GetIntegerv, and GetInteger64v:

        PATCH_VERTICES                                 0x8E72
```

It is used to define the amount of vertices (or "control points") per primitive in every patch. (See also https://www.opengl.org/sdk/docs/man/html/glPatchParameter.xhtml).

I think a `Mesh& Mesh::setPatchVertices(int i)` and `int Mesh::patchVertices()` should be sufficient. I might do this myself once I find time.

Regards, Squareys.

**Comment by mosra** [comment]
Hi,

yes, this is mentioned in the [OpenGL Support State](http://mosra.cz/blog/magnum-doc/opengl-support.html#opengl-support-40) doc page and as far as I know this is the last missing bit in order to have complete tessellation support. I didn't include it originally because I was not sure what exactly it does and how is the desired usage. With your explanation now I get it :)

If I'm reading the specification correctly, this is a global state and not VAO-specific state, so it can't be in `Mesh` but has to be in `Renderer`. Putting it in `Mesh` would falsely suggest that the state stays kept for the next draw, which is not true.

*(That reminds me you also requested the primitive restart API some time ago. Can you open another issue for that so I don't forget again?)*

**Comment by mosra** [comment]
Done three and half years ago in cc401b2b3cc834b623abc191a8e60568d6425464. Since nobody else requested primitive restart in the last five years, I assume that feature is absolutely non-critical :)
