### ISSUE TITLE
Magnum components do not propogate up module folders

### ISSUE THREAD

**Issue by Alicemargatroid** [mosra/magnum#170]
This may be in the wrong section, but I don't know where else to put it.
When using Magnum as a subproject (as shown in the tutorials), Mangum, Magnum-Plugins, and Mangum-Integration do not properly add their own personal modules folder to the MODULE_PATH.
This results in a _ By not providing "FindMagnumIntegration.cmake" in CMAKE_MODULE_PATH this_ error.

The reason is this line (and similar in other projects): `set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${PROJECT_SOURCE_DIR}/modules/")`

When Magnum, Magnum-Plugins, or Magnum-Integration is used as a subproject, this will not add their respective modules folder; it will instead add the top level modules folder several times.

Two solutions present themselves:
1. Add FindMagnumPlugins and FindMagnumIntegration (and any similar) to the Bootstrap modules folder
2. Modify the current line to use ${CMAKE_CURRENT_SOURCE_DIR}, to make it add the correct folder

**Comment by mosra** [comment]
Thanks for the report. Yes, I am aware of this.

However I think the problem is somewhere else. The `${PROJECT_SOURCE_DIR}` variable will evaluate to the nearest current-or-parent directory that has a `project()` command in it, so in case of the subprojects, this will evaluate to e.g. `<the-dir-where-you-dump-all-the-git-repos>/magnum-bootstrap/magnum`, `<the-dir-where-you-dump-all-the-git-repos>/magnum-bootstrap/magnum-plugins` etc., *not* the root dir of the topmost project (that would be the `${CMAKE_SOURCE_DIR}`). In fact, some time ago, before the subprojects were supported, there actually was `${CMAKE_SOURCE_DIR}` instead of `${PROJECT_SOURCE_DIR}` everywhere and was causing the very problem you are describing (the top-level `modules/` folder added several times).

I think the problem here is that the result of the `set()` command is not propagated to parent directories, so they can't see any new folders added to `CMAKE_MODULE_PATH`. One could use the `PARENT_SCOPE` keyword, but that may not be wise to do, because it unconditionally affects the parent project (imagine what could happen if one of the subprojects overrode some builtin module with some completely different version, causing user code to break in random ways).

So -- I don't want the subprojects to implicitly affect the parent project by using `set(CMAKE_MODULE_PATH .. PARENT_SCOPE)`, thus then the only option is to add all the modules you need to the bootstrap modules folder. For the projects that are provided in the `magnum-bootstrap` that's not done *by design* -- the bootstrap repos are designed to have the smallest possible amount of files and code to start building an application, nothing optional on top. So you have to copy the files to the module dir manually yourselves, I guess.

If there is any other option that I missed, please let me know.

Uh, I got verbose today. Sorry.

**Comment by Alicemargatroid** [comment]
@mosra Maybe providing the `FindMagnumPlugins.cmake` and `FindMagnumIntegration.cmake` files with the bootstrap project would be an acceptable cost to that purity? Or at least adding a line into the tutorials about it somewhere?

I understand the problem with CMAKE's variables not propagating though, something I hadn't realized.

**Comment by mosra** [comment]
There's a bunch of info about copying the modules in each Usage with CMake chapter, e.g. [here](http://mosra.cz/blog/magnum-doc/cmake-plugins.html). I also recently added some info about the extra CMake modules at the bottom. I admit the documentation is *huge* and even though it might be mentioned in some place, it is hard to find (and it will not get better with the project growing more), so if you can suggest a better place where I should stress this requirement, please do :)

There's a bit of dependency hell with the `Find` modules -- to make it really working out of the box in all cases, besides those two I would need to provide also `FindOVR.cmake`, our fork of `FindFreetype.cmake` and `FindOpenAL.cmake`, `FindHarfBuzz.cmake`, `FindNodeJs.cmake`  etc. etc. and that's just too much :(

So if you are okay with just this requirement being clearly mentioned in the docs, I'll happily put more words there.

**Comment by mosra** [comment]
Added a note about additional modules to the Getting Started guide in 0125d32e5e797e857c08f87c9b22a174f11cd8fe.

**Comment by Alicemargatroid** [comment]
@mosra More than sufficient!
