### ISSUE TITLE
TMP wrappers for Math types require basic comparator implementations

### ISSUE THREAD

**Issue by jaynus** [mosra/magnum#182]
I'm currently working with http://github.com/ThePhD/sol2/ Lua wrapping framework for a project.  The framework heavily leverages templates and TMP to build out lua wrappers for base types. 

For the Magnum::Math::Vector<T> base types, this includes needing basic operator return values for automatically wrapping operators. The Vector<T> types currently only implement returning BoolVector, and BoolVector is not naturally deducible to a primitive type (bool). 

In a nutshell - the library attempts to deduce all the basic natural operators on a type ( =, *, /, etc) in their standard form. This obviously fails, as the boolean operators on Vector do not in fact return booleans.

This has three solutions:

**Solution 1**
Implement an operator bool() on BoolVector for returning proper results for default operators. I've done this for now in my project, by implementing 
``` 
constexpr operator bool () const { return all(); }  
```
as an operator on BoolVector<T> in Math\BoolVector.h

 **Solution 2**
Implement the proper "actual" primitive operators in the Vector base templates. 

**Solution 3**
I instead look into the library (sol2) and see if its a improper assumption on their part. Personally, I dont think it is - and this is a single-operator fix in Magnum.

**Comment by mosra** [comment]
Hi!

Oh, cool, Lua wrapper!

What a coincidence, I need this exact behavior for properly implementing `>=` etc. comparisons in TestSuite. I originally did not put any boolean conversion into `BoolVector`, because it was unclear which one of them should it be, whether `any()` or `all()`. However now I'm pretty sure having it equivalent to `all()` makes perfect sense.

One thing, though: I would like to make the conversion operator `explicit` to prevent accidents like `(a > b)*3` to compile:

```cpp
explicit operator bool() const { return all(); }
```

Would this also work with the wrapping framework?

**Comment by jaynus** [comment]
Yup! I can confirm it will take explicit as well - This applies to both sol2 and Selene, I am actually experimenting with both so I have a unit test for this anyways.

**Comment by mosra** [comment]
Done in cf185b00fa929c09a13294b899bef834c0d23377. I just had to wait for the CIs to verify that I did not hit any nasty ambiguity with MSVC (had a few of those in the past with bool conversion operators).
