### ISSUE TITLE
Redefinition of OpenGL symbols, with Qt on OSX

### ISSUE THREAD

**Issue by notsimon** [mosra/magnum#212]
Hi,

I'm using the Qt base project from magnum-bootstrap, on OSX 10.11.6. Here's an extract of the errors I'm having:

```
In file included from src/MyApplication.cpp:5:
In file included from /usr/local/opt/qt/lib/QtWidgets.framework/Headers/QOpenGLWidget:1:
In file included from /usr/local/opt/qt/lib/QtWidgets.framework/Headers/qopenglwidget.h:49:
In file included from /usr/local/opt/qt/lib/QtGui.framework/Headers/qopengl.h:131:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:1750:21: error: 
      redefinition of 'flextglBlendColor' as different kind of symbol
GLAPI void APIENTRY glBlendColor (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
                    ^
magnum/src/MagnumExternal/OpenGL/GL/flextGL.h:2479:22: note: expanded from macro 'glBlendColor'
#define glBlendColor flextglBlendColor
                     ^
magnum/src/MagnumExternal/OpenGL/GL/flextGL.h:2478:37: note: previous definition is here
GLAPI FLEXTGL_EXPORT void(APIENTRY *flextglBlendColor)(GLfloat, GLfloat, GLfloat, GLfloat);
```

The same error appears for many other `flextgl...` symbols. Do you have any idea of what might be going on ? I don't have any issue when building a GLFW application.

**Comment by mosra** [comment]
Hi, thanks for the report!

I created this project on a Linux system and there was no such issue, except that I had to include the Magnum headers first in order to avoid a similar issue but the other way around. I just verified again and it's still compiling fine on Linux. This is unfortunate -- I assumed Qt is sane enough to behave similarly on all platforms, but somehow it isn't.

Just to be clear -- Magnum `#define`s all the `glSomething` function symbols as preprocessor aliases to `flextglSomething` function pointers in order to properly load those function pointers on startup. Qt should be clever enough to see that those symbols are already defined and not try to redefine them in a different way. For some reason, this is happening only on macOS.

I currently don't have any direct access to a macOS system, so I'll try to reproduce and investigate this at least remotely via Travis CI. Will post an update when I'm done.

**Comment by mosra** [comment]
I did some trial-and-error on Travis and apparently defining `__gl3_h_` before including anything from Qt solved this problem.

Can you confirm this? If this works for you as well, I'll put the define into the engine GL headers. Thank you!

**Comment by notsimon** [comment]
Hi,
Thanks for your help ! It works perfectly with the `#define __gl3_h_`. :)

**Comment by mosra** [comment]
Thanks for the confirmation! :) 

Pushed as 2384d5cccdb020342ad9ad6d40d700c7586acbc1 into master.
