### ISSUE TITLE
Make Buffer::setData more convenient 

### ISSUE THREAD

**Issue by AndySomogyi** [mosra/magnum#213]
Currently, the `Buffer::setData` is not very convenient when it comes to non-static user data, i.e. 

```
std::vector<Vector3> vertexData = {...}
vertexBuffer.setData(
    Corrade::Containers::arrayView(vertexData.data(), vertexData.size()),
    BufferUsage::DynamicDraw);
```

If this were just a plain old OpenGl call, it would be:

```
std::vector<Vector3> vertexData = {...}
void glBufferData(GL_ARRAY_BUFFER,  
    vertexData.size() * sizeof(Vector3), vertexData.data(), DYNAMIC);
```

So, why not just add an overloaded version of setData that has the first two args are void& and size_t? This would make it move convenient than having to bring in `Corrade::Containers::arrayView`, so, it could be like: 

```c++
std::vector<Vector3> vertexData = {...}
vertexBuffer.setData( 
    vertexData.data(), vertexData.size(), BufferUsage::DynamicDraw);
```

Also, the templated flavor buffer::map is not very consistent with setData. With setData, the ArrayView template takes care of figuring out the type size, so the size argument refers to the number of items, NOT the size in bytes (this really confused me). However, the Buffer::map template requires a size in bytes to map the buffer, i.e. 
```c++
 // map the buffer
Vector3* mapped = vertexBuffer.map<Vector3>(0,  particles * sizeof(Vector3),
    Buffer::MapFlag::Write|Buffer::MapFlag::InvalidateBuffer);
```

The template here could readily take the size of the template argument into account. So, I think either both setData AND map should use a count and let the template figure out item size, or both use a size in bytes. The docs too I think should better explain whether to use item count, or size in bytes.

**Comment by mosra** [comment]
Hello -- sorry for the late reply.

I think it's not *that* inconvenient with `Buffer::setData()` -- you can either pass `std::vector` directly (and there is an overload for `std::array` as well):

```cpp
std::vector<Vector3> vertexData = {...};
vertexBuffer.setData(vertexData, BufferUsage::DynamicDraw);
```

Or you can use C++11 uniform initialization syntax, if you happen to have some container that is not `std::vector`, not `std::array` and is not convertible to `Containers::ArrayView`:

```cpp
vertexBuffer.setData({vertexData.begin(), vertexData.size()}, BufferUsage::DynamicDraw);
```

I find the above superior to having yet another overload that is just accepting a `void*` and `std::size_t` like GL does, because one would then have to make sure to not forget to multiply with `sizeof(T)`.

Regarding `Buffer::map()`: yes, the current situation is very confusing. I think I will probably deprecate the templated overload to make it clear that both the offset and size is in bytes. Moreover, I missed the opportunity to make the `map()` function return `Containers::Array` with a custom deleter that calls `Buffer::unmap()` when going out of scope. Or at least make it return `Containers::ArrayView` with *both* pointer and size. Oh well.

I thought about the `map()` function quite a lot when doing the implementation -- the offset *has to be* in bytes, because the offset might not always be a multiply of type size. Then, having the offset as bytes and size as count would be equally confusing.

So I guess the only possible way that doesn't break silently is to deprecate the templated `map()` function (and related), make the non-templated function return `ArrayView` and encourage users to use `Containers::arrayCast()` on the result. What do you think?

**Comment by AndySomogyi** [comment]
I think there are two basic kinds of use cases here: a) statically known vertex buffer layout, and b) dynamically known vertex buffer layout. 

For case a, the C++ template/type system can certainly do a lot for simplifying vertex buffer access, as the template system can figure out things like stride, offset, type, etc. and expand to the appropriate gl values. However, for case (b), the template system can't know anything about data types, as these are only known at run-time. 

In my case, 1) the binary layout of the mesh data will is determined at run-time, and 2) the shaders will also be generated at run-time. At compile-time, I know basically nothing about the layout of the mesh, or what kinds of vertex attributes the shaders are expecting.  

I think it would be really nice to have an overload of the standard low-level opengl functions on the Magnum::Buffer and Magnum::Mesh, but take advantage of Magnum's gl state handling (not have to worry about all the glBind... stuff).  

So, a plain old 

```void* Buffer::map(GLenum access)```,
 
and 

``` void* Buffer::map(GLintptr offset, GLsizeiptr length, GLbitfield access)```, 

would really work the best for me. 

For Magnum::Mesh, an overload like 

```Mesh::vertexAttrib(Magnum::Buffer&, GLint attribIndex, GLint size, GLenum type​, GLboolean normalized​, GLsizei stride​, const GLvoid * pointer​);```

As for the static case, let`s say your vertex format is something like:

```
struct MyVertex {Vector3 pos, Vector3 norm, Color4 color ...}
```

and say you want to create a vertex buffer, let opengl allocate it, but hold off filling it. Then I think this would work:

```
vertexBuffer.setData({(MyVetex*)nullptr, 666}, BufferUsage::DynamicDraw);
```

Here, 666 would be your total vertex count,  and I think the ```ArrayView``` template already takes care of this of figuring out the size of the data MyVertex struct. But, this syntax, I think would be the clearest, where you just give a typed statically data pointer, and a count, and let the template figure out the size in bytes. Corresponding to this, a templated map function could work like this, say we wanted to grab the last half of the vertex buffer:

```
MyVertex* p = mesh.map<MyVertex>(333,665,flags);
```
The map<> template argument would know that you're asking for a statically typed pointer, hence the and the arguments are interpreted as counts, rather than sizes. 

But, in either case, I think as long as both the statically typed addVertexBuffer and map both operate on counts, rather than sizes, then it's consistent, and the dynamically typed, low-level flavors of these operate on sizes (as stride is not known until​ runtime), then these two are consistent.

**Comment by mosra** [comment]
> So, a plain old
>
>    void* Buffer::map(GLenum access),
>
> and
>
>    void* Buffer::map(GLintptr offset, GLsizeiptr length, GLbitfield access),
>
> would really work the best for me.

Yup, these are there, only with strongly-typed enums. Just not use any `<>` and it will be like this.

That's the same with passing `{(MyVertex*, nullptr}`, it should work properly as well.

However, with the dynamic layout you are right -- the least you need to have is a static location and underlying type, the rest can be done dynamically. For now, until I fix this, a solution could be a sequence of `typedef Attribute<N, Vector4> AttributeN` or something, having some switch over these and then controlling the concrete component count and data type using dynamic `Attribute::Components` and `Attribute::DataType` params (see Mesh docs for details). Similar for e.g. integer types.

Regarding the templated map: I just *can't* silently change the semantics of offset/size params -- that would break a lot of code (having some enterprise customers that wouldn't be happy with this) so I need to find another solution that doesn't break current behavior. Hope you understand.

I'm travelling right now, so I won't be able to provide the updated API until Wednesday evening the earliest. Is that okay?

**Comment by AndySomogyi** [comment]
No hurry. 

Now that I've figured out some of the discrepancies, what I have is working. I'm also very early in dev stage, so no big deal if API changes. 

On thinking about this a bit further, and adding a bit more examples, consider this. When one uses virtually any c++ std lib container, it's invariably going to be count oriented -- based on the number of elements, regardless of size. Conversely, nearly all 'lower level' OpenGl, DirectX, libc, etc..., are going to be size, rather than count oriented. They're going to depend on the total buffer size, hence we're dealing with bytes, and not counts. 

There are clear use cases for *BOTH*, the trick is how to cleanly distinguish between them, so it's clear from a user's perspective what to do. 

As for the ```Buffer::map``` change, to me, it seems like the signature of the current version definitely puts it in the count rather than size category. But as you said, the semantics behave as a size oriented method, and there could be current users. So, how about this: One option is to create a macro, something like ```BUFFER_MAP_OLD_STYLE```, and default it to true. If true, the Buffer::map works as is, but if not set, then Buffer::map is count oriented, and picks up the size from the template argument. 

One option to support both statically typed, count oriented high level, and run-time typed, byte size oriented low-level behaviors is to have a different naming convention on them. The high-level ones, are the exiting Magnum, nicely named ones, and you could add the low level ones by following OpenGl's naming conventions.

**Comment by mosra** [comment]
So, this is what I did in the end. It kinda blew up, because I discovered that the `Containers::ArrayView` API is error-prone and had to patch it as well in order to make this possible.

Regarding buffer mapping etc.:

- The templated versions of `Buffer::data()`, `Buffer::subData()` and `Buffer::map()` are deprecated now in favor of the non-templated ones. The non-templated version of `Buffer::map()` now returns `Containers::ArrayView` instead of just a naked pointer and the suggestion is to use `Containers::arrayCast()` on the returned view to get the type you want. This has an additional benefit that you don't lose the size information along the way and there's also some protection against casting to completely types that won't match the mapped memory size. Commit 944b068f6da11ef326b5a5e85308334c2506911c.
- In addition, there's new `Buffer::mapRead()` convenience function that returns a `const` array view (c576644c9f66cd8915ab09db2807846f5c57e6a1)

All offset/size parameters of the whole `Buffer` API are in bytes now. I'm not adding any additional templated overloads like `mapData()`, because they would only ever offer a limited functionality. Consider this case, where you have a buffer of this structure:

```cpp
struct Data {
    Int a[30];
    Vector4 b[40];
}
```
and you want to map the contents of `b` with a hypothetical `map<Vector4>(offset, size)`. If both `offset` and `size` would be in counts of `Vector4`, it would be impossible to perform the mapping, as `b` doesn't start at multiples of `Vector4` size. The `offset` would need to be in bytes instead to make this possible and that's basically going back to the confusion. So there's just bytes everywhere now -- more clear, smaller API surface area, but more typing on user side.

I also wanted to keep things simple and maintainable, so going this way was the only option I think. Adding `BUFFER_MAP_OLD_STYLE` macro or similar would mean the user code could behave differently depending on what package maintainer decided to define when compiling magnum for a particular system and in order for user code to be portable, one would need to handle both cases of the macro definition. That's *seriously bad* thing to introduce to the API, I hope you understand ;)

Regarding dynamic attributes: commit f1982f2e1bf64c7e36f8db62bcf67c3fe4d486b7 introduces a new way to specify vertex attributes, check out the docs and tests to see the difference to current API. I tried to test every case I'm testing with the `Attribute` class also with the new `DynamicAttribute` class, so there should be no difference in amount of bugs when using one or the other.
