### ISSUE TITLE
GlfwApplication::setTitle missing

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum#230]
Hey @mosra !

Looks like I forgot to add this method. It's a simple call to `glfwSetWindowTitle`, I may do that once I find time to test the changes proposed in #194 and attach the changes to that PR.

Cheers, Jonathan.

**Comment by Squareys** [comment]
@mosra I wonder what I was refering to here... there is no Sdl2Application::setTitle() 🤔

**Comment by mosra** [comment]
Ha, yeah, there's no `setTitle()` anywhere, it's at the moment only possible to set a window title through the `Configuration` when creating the window, not changeable later ... and [GlfwApplication::Configuration::setTitle()](http://doc.magnum.graphics/magnum/classMagnum_1_1Platform_1_1GlfwApplication_1_1Configuration.html#a362858c34fa03931d6924bb30a009022) *is* there.

Two options:

- go all the way and implement runtime `setTitle()` for all the App classes
- close this, because ... do we urgently *need* this at the moment? :D

**Comment by Squareys** [comment]
> close this, because ... do we urgently need this at the moment? :D

Thanks :D
