### ISSUE TITLE
2D / pixel coords, vcpkg plugin workflow

### ISSUE THREAD

**Issue by kdezz** [mosra/magnum#235]
hi

are there any examples on how to use 2d or pixel coords with magnum?

**Comment by mosra** [comment]
Hi! :)

I was working with a friend on a 2D game some years ago, but it got abandoned since and I didn't see the code since. Here you go, in case you want to have a look (there's even a very WIP WebGL demo): https://github.com/nuclearwhales/rottennoodlessmuggler

Besides that, here's a bunch of things to check out for 2D things:

- [Matrix3](http://doc.magnum.graphics/magnum/classMagnum_1_1Math_1_1Matrix3.html), [Complex](http://doc.magnum.graphics/magnum/classMagnum_1_1Math_1_1Complex.html), [DualComplex](http://doc.magnum.graphics/magnum/classMagnum_1_1Math_1_1DualComplex.html), [Vector2](http://doc.magnum.graphics/magnum/classMagnum_1_1Math_1_1Vector2.html) for transformations in 2D (or see [the introduction page](http://doc.magnum.graphics/magnum/transformations.html))
- Using pixel coordinates is just a matter of setting up the projection size to be the same size as your window, use [Matrix3::projection()](http://doc.magnum.graphics/magnum/classMagnum_1_1Math_1_1Matrix3.html#a8a782bf6187750b0f4bc763623ee3857) for that, you might also want to move the origin to bottom left or top left instead of center
- You can use [SceneGraph::TranslationTransformation2D](http://doc.magnum.graphics/magnum/classMagnum_1_1SceneGraph_1_1TranslationTransformation.html) on an integer type if you want to snap your transformations to pixels (but you don't have to)
- Some examples such as [Text rendering](http://doc.magnum.graphics/magnum/examples-text.html) or the [UI gallery](http://magnum.graphics/showcase/magnum-ui-gallery/) might give further hints how to handle 2D stuff

Hope this helps :)

**Comment by kdezz** [comment]
thx for so much info. whats the best way to get plugins working with vcpkg? trying the text render example but having problems with that.

**Comment by mosra** [comment]
What exact error are you getting? Are you using CMake or just Visual Studio directly? The dynamic packages were written to hopefully "just work", if you use the static build, some additional patching might be needed.

**Comment by kdezz** [comment]
vs no cmake, think thats the issue all the docs is for cmake. im doing the install via vcpkg same as normal magnum, trying to set manager initialization to the plugin directory, doesn't seem to work. not sure if it's supposed to be autoconfigured or theres some define or something? i have both static + dynamic installed and use dynamic during dev for that reason (just works).

**Comment by mosra** [comment]
> all the docs is for cmake

Yeah, it's a historical reason, I'm in process of slowly updating all the places currently.

I am not directly involved in creating the Vcpkg packages, just watching it from distance, but so far I think that all the DLLs (including plugins) are copied along the executable. Or maybe the plugin DLLs are somewhere in `C:/vcpkg` and by accident not copied, I'm not exactly sure at the moment. @Squareys did the package, so pinging him here :)

In case they are copied along, try to set the plugin directory relative to the exe using [Corrade::Utility::Directory::executableLocation()](http://doc.magnum.graphics/corrade/namespaceCorrade_1_1Utility_1_1Directory.html#a4e3dbc86c7b8d0c3c39d9802a9947b35). In case of the text example it could be this change:

```cpp
#include <Corrade/Utility/Directory.h>

// ...

TextExample::TextExample(): ..., _manager{Utility::Directory::join(Utility::Directory::executableLocation(), "magnum/fonts/")}, ...
```

Also, (just in case you didn't already do this), ensure that you have some font plugin installed (they are not installed by default), for example:

```bat
vcpkg install magnum-plugins[stbtruetypefont]
```

It's on top of my priority list to implement some sort of autodetection for plugin location so you don't have to go through the location setup, but so far I didn't get to it yet. Sorry about that.

**Comment by kdezz** [comment]
managed to get it to find it now (btw executablelocation() the process name including extension) but now 

`PluginManager::Manager::load(): cannot open plugin file "C:/Users/kd/Documents/MagnumTest/x64/Debug/magnum/fonts/FreeTypeFont.dll": 126` which is ERROR_MOD_NOT_FOUND but its definitely @ that directory. maybe its because corrade/magnum appends forward slash which windows doesn't like? i have a feeling this is linux vs windows issue.

unfortunate there is no way for me to quickly test this change as i would need to rebuild whole library.

**Comment by mosra** [comment]
> btw executablelocation() the process name including extension

argh sorry, of course, it's too late for me :D

I'm pretty sure forward slashes work (never had a problem with plugin loading on windows). The "not found" error might be also due to some dependent DLL not being found (I suspect FreeType DLL or some dependency of FreeType is not found). Just as a last resort, could you try with the `StbTrueTypeFont` plugin I mentioned above? It has no external dependencies, just install it and change the code to `loadAndInstantiate("StbTrueTypeFont")`.

**Comment by kdezz** [comment]
universe doesnt want me to win (when installing stbtruetypefont plugin): `Cycle detected within graph:
    magnum-plugins:x64-windows`

**Comment by ras0219-msft** [comment]
That's a vcpkg bug! Can you let me know the command line so I can repro it on my side? Also make sure you're using the latest master and re-run `bootstrap-vcpkg.bat` -- we did fix some bugs in that recently :)

**Comment by mosra** [comment]
wow, @ras0219-msft, thanks, you were faster than me :+1: :D 

I have a hunch that it's related to the Build-Depends [line here](https://github.com/Microsoft/vcpkg/blob/d4797b37a624f190e6a8e5a6519d2d0add282634/ports/magnum-plugins/CONTROL#L76) (deleting it might make it work?), command-line is the following while having Magnum installed:

```bat
vcpkg install magnum-plugins[stbtruetypefont]
```

**Comment by kdezz** [comment]
@ras0219-msft so you need to have base feature installed like `magnum-plugins:x64-windows` or in my case `magnum-plugins[freetypefont]:x64-windows` and then try to install another feature from the same like `.\vcpkg.exe install magnum-plugins[stbtruetypefont]:x64-windows` i was outdated but i just git pulled + ranbootstrap and it still happened.

**Comment by kdezz** [comment]
@mosra yes `StbTrueTypeFont` works, its a dependency problem not forward slash.

**Comment by mosra** [comment]
Okay, great to have this narrowed down :)

@ras0219-msft since you are here, can I ask a question? :) If I have a plugin DLL automagically copied (i.e., one loaded exclusively with `LoadLibrary`) to the executable output directory, will also all its dependencies get copied? Such as, in this case, the FreeTypeFont plugin needs the FreeType DLL to work, but it doesn't seem to be there.

**Comment by ras0219-msft** [comment]
It depends on how you automagically copy it -- we actually had a bug in the way we handled Qt because we _weren't_ following through with their plugins :) However, I've since fixed that issue so I definitely know how to make it work!

I unfortunately don't recall at this point whether we built a similar deployment script for magnum, so I don't think this is currently handled correctly.

**Comment by kdezz** [comment]
@mosra i did move freetype.dll into the local directory and still no luck. does FreeTypeFont plugin search for "freetype.dll" or another name? and does it search the local relative dir?

**Comment by mosra** [comment]
@kdezz As far as I know, FreeType had a dependency on libpng, zlib and bzip2, so you need these DLLs as well. Hopefully these are all needed :)

@ras0219-msft  Awesome :) Can you point me to the relevant part of deployment script you have for Qt so we can see what's needed to make it work? It's 2 AM here, so I doubt I will make any significant progress now, but either me or @Squareys might ask for assistance the next days when fixing this :) Thank you!

**Comment by kdezz** [comment]
no luck with those deps added manually. https://i.imgur.com/vp6du9X.png

**Comment by mosra** [comment]
Ah, these need to be located next to the application executable, not in the plugin subfolder.

**Comment by kdezz** [comment]
same error even with them next to the executable :(

**Comment by kdezz** [comment]
i only needed the font system to try the example and mess with 2d stuff, but in this issue time i have read a lot of magnum docs and im getting a foundation of 2d working no problem so no need for text right now. i can certainly use `StbTrueTypeFont` until then if required

your help and quick reply is amazing, thx so much

**Comment by Squareys** [comment]
I'm on this now! 

@ras0219-msft Currently having a weird problem where dependencies aren't being built though:
~~~
vcpkg install magnum[sdl2application] # Fails because sdl2 is not found during cmake configure
vcpkg install sdl2 # Sais it was installed, though libraries are not in installed/x64-windows
vcpkg remove sdl2 && vcpkg install sdl2 # works properly
vcpkg install magnum[sdl2application] # Now works fine, if dependency was explicitly installed
~~~

**Comment by Squareys** [comment]
Okay, so I found out that vcpkg automatically copies all required DLLs into the folder of the built executable when using the toolchain, which is pretty cool!
When trying to build the text example, though, I run into two Problems:
 - SDL2.dll is not copied (and neither is MagnumSdl2Application, because that is linked statically always. Its dependencies should still be copied, though)
 - vcpkg does not have any way of figuring out that the application in using the FreeTypeFont plugin and would never know that it should be copying its dependency: freetype (and its dependencies: libpng, libz...)

The first one sounds like a more obvious problem. The second one I would personally work around by adding `<...>\vcpkg\installed\x64-windows\lib` to `PATH`, as I don't see a way how this would be solvable on vcpkg side. (The plugin is merely referenced by a String in the C++ code.)

**Comment by mosra** [comment]
> I don't see a way how this would be solvable on vcpkg side.

[This script](https://github.com/Microsoft/vcpkg/blob/11d4a5c47edb75c8aaaa7d86bc2d351af8b32e28/ports/qt5/qtdeploy.ps1) is apparently solving this, basically copying all plugins related to whatever lib you seem to be using in your code. I guess we need something like that here as well.

**Comment by Squareys** [comment]
>  is apparently solving this

So suppose you are doing `manager.loadAndInstantiate("FreetypeFont")`, but only have StbFreeTypeFont installed (in case that's a thing). How would you figure out that you are referencing that?
Basically we would need to know what PluginManager would do, replicate that in CMake and then copy the dependencies for the plugin that would be loaded.
And all that by parsing user code for `load(*)/loadAndInstantiate(*)`?

I want to say, this is not that simple.

**Comment by ras0219-msft** [comment]
Our approach for Qt has been to copy every possibly referenced plugin (this isn't perfect, but it works). Specifically, whenever we see that your application references `QtNetwork.dll`, we deploy every binary in the `plugins/bearer/` directory, then deploy any of _their_ dependencies into the original application directory.

**Comment by Squareys** [comment]
Alright, yesterday I had a go at this and will add a magnumdeploy.ps1 script to deploy the plugins correctly. Expect a pullrequest soon.

**Comment by Squareys** [comment]
@ras0219-msft I have not yet been able to figure out how to debug the applocal.ps1 script. Where do I find the output of `Write-Verbose`? (I have as good as no previous powershell experience).

I tried increasing the MSBuild verbosity level [as explained here](https://github.com/Microsoft/vcpkg/blob/master/docs/users/integration.md), but that did not seem to have helped. Even when changing `Write-Verbose` to `Write-Information`, that does not seem to yield any output in the Visual Studio build output.

**Comment by mosra** [comment]
Loading dynamic plugins got much simpler now, no need to pass in the plugin directory anymore ([details](http://blog.magnum.graphics/announcements/plugin-usability-improvements/#autodetected-plugin-paths)).

That means only the plugin dependency copying remains to be done now.

**Comment by Squareys** [comment]
Proposed changes to fix the deploying of plugins with https://github.com/Microsoft/vcpkg/pull/3191 🎉 

As far as I understand there is an upcoming change which will allow finding the plugins relative to the executable and then the vcpkg workflow with plugins should be perfectly smooth.
(Or is that change already on master, @mosra?)

**Comment by mosra** [comment]
Since the plugin workflow updates are shipped and the vcpkg changes are merged, I think I can close this :beer:
