### ISSUE TITLE
Metal backend

### ISSUE THREAD

**Issue by wivlaro** [mosra/magnum#254]
No hint as to whether it will be removed, but it's worth noting that OpenGL ES is deprecated in iOS 12 and OS X (Mojave). https://developer.apple.com/ios/whats-new/ and https://www.pcgamer.com/developers-fear-for-mac-gaming-as-apple-deprecates-opengl-support/

Could we use KhronosGroup/MoltenVK? Do we already know if would work already? Is it worth making sure magnum is compatible with MoltenVK?
Is a Metal backend completely out of the question?

**Comment by mosra** [comment]
Hey, happy to see you around again :)

Yes, I'm *very* aware of this deprecation, the even funnier part is that they deprecate OpenCL, a *standard* that they actually created.

Yes, I'll be making sure the Magnum Vulkan backend is able to run with MoltenVK. As far as I'm aware, MoltenVK has full Vulkan compatibility except for minor things like not being able to use triangle fans or something like that. There's also [MoltenGL](https://moltengl.com/) from the same creator, but there's little info on how fast, stable or conformant it is. Well, until someone buys it out like they did with MoltenVK :)

A dedicated Metal backend is not out of question, though I'd rather invest more time into open technologies that can be used on more than one platform instead of spending that time on creating a new backend from scratch -- and at this point I think MoltenVK will suffice. The surface area of the Vulkan API is quite small and there's a lot of room for optimizations with pipeline caching and everything, so I think the performance implications from translating Vulkan to Metal will be minimal.

**Comment by mosra** [comment]
Because there's always more things to do than there's time, I have decided to not invest into APIs that are available only on a single platform, thus Metal and D3D (#262) is currently out of question. The time will be spent on Vulkan and WebGPU instead.
