### ISSUE TITLE
How to interact with magnum in another thread?

### ISSUE THREAD

**Issue by scturtle** [mosra/magnum#258]
I want to receive messages from another process/thread and add object in magnum. What's the right way to use magnum in multi-thread environment?

I tried this following code but got runtime error in creating shader:
```c++
void recv_msg(Vis *vis) {
    vis->add_plane();
}

int main(int argc, char **argv) {
    Vis vis({argc, argv});
    std::thread th(recv_msg, &vis);
    vis.exec();
}
```

I also tried replacing `exec()` with while loop and `mainLoopInteraction()`. But the latter function is also blocking.

**Comment by mosra** [comment]
Hi,

OpenGL context is restricted to be used from a single thread only. That's how OpenGL works, unfortunately, and there is little Magnum can do about it. Some possibilities:

- Have a single OpenGL context, use it only from one (main) thread. All other threads need to avoid touching any GL state -- for example only pass messages to the main thread, which then does requested OpenGL calls. For example, you can have a memory buffer (in CPU memory) which you fill from the other thread but it gets uploaded to `GL::Buffer` from the main thread. That's the most common way, least error-prone, most widely supported yet still quite efficient way of doing this.
- Have a single OpenGL context and use it only from the main thread, but pass pointers to GPU memory to other threads to fill. For example you can map the `GL::Buffer` from the main thread, pass a pointer to it to the other thread and fill it from there, then unmap / flush it again on the main thread. Or map the buffer persistently. This is probably the fastest possible way to do things, but you need to ensure memory access and buffer mapping is properly synchronized. Persistent mapping also requires quite recent GPU architectures / drivers (and the [glBufferStorage()](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBufferStorage.xhtml) command, needed for persistent mapping, is not yet implemented in Magnum, though adding such support isn't hard -- and you can also just call it directly).
- Have a single OpenGL context and make it current only on a thread that needs to use it. That's quite error-prone and slow if done frequently -- you have threads, but the work is done serialized anyway. Magnum currently doesn't support this because it doesn't really help with anything (though adding such support is trivial, you can also call the platform-specific `xglMakeCurrent()` APIs directly).
- Have multiple shared OpenGL contexts, each bound to a single thread and share *some* GL objects among them. Sounds cool in theory, but unfortunately in practice this often means the driver is still doing things serialized, so you don't get any performance gains. Moreover, not all objects can be shared -- buffers and textures can be, but not for example meshes or framebuffers. Because of the questionable benefits, Magnum doesn't support this use case (but you can always create shared GL contexts manually).

**Comment by scturtle** [comment]
Thx!
