### ISSUE TITLE
Feature request: wrap around for angles

### ISSUE THREAD

**Issue by kghose** [mosra/magnum#264]
The `Deg` and `Rad` units are great. It would be very convenient if the arithmetic operators for these angles would wrap around ([0, 2*pi]). Not sure if this would break someone's code, but I tend to like wrapping for angles since `x` and `x + 2pi` are equivalent for any operations they are actually used as angles, which is what these are for. Thanks!

**Comment by Guillaume227** [comment]
Indeed, that would be cool. 
However that request seems at odds with the approach used for Deg and Rad, known as "strong typedef". Beyond the safety offered by the typesystem, variables in those units are compiled as some floating point type. 
Adding wrap around-logic would make that zero cost approach impossible.
For example adding two such variables would have to trigger some wrap-around check which can't be compiled down to just adding two floats.

**Comment by mosra** [comment]
The idea, in theory, seems cool. 

The loss of "zero-cost abstraction" is a valid point. At the moment, I would expect that *heavy* use of Deg/Rad (i.e. in some algorithmic-heavy code that gets inlined in a lot of places) would increase compile times quite a lot, so the zero-cost is probably only at runtime with optimizations enabled. With the wraparound that would be lost too.

However, I'm more concerned about accumulation of numeric error than loss of zero-cost abstraction. Depending on the use, the accumulated error might get quite high due to all the subtraction (and probably much more with Rad types than with Deg, because a circle in radians can't be represented exactly in binary). And since the wraparound would be done in the background, there would be no easy way to combat that error. This is also the reason why algorithms such as Kahan Sum (here implemented as [Math::Algorithms::kahanSum()](http://doc.magnum.graphics/magnum/namespaceMagnum_1_1Math_1_1Algorithms.html#aa4696c9d956d5c6bb1833a29533be545)) exist -- one very pathologic case is shown in the documentation code snippet.

**Comment by Guillaume227** [comment]
Numeric error accrue when adding a big float to a smaller one, causing truncation right?
If anything, I would think wrapping around, i.e. restricting values to the same range of exponent (roughly 0-4 for rad and 0-360 for deg) would provide a natural mitigation of such errors, without going for Kahan explicitely?

i.e. we would never be in a situation to add 999999999999_rad and 1.334356rad.

**Comment by wivlaro** [comment]
Programmers have to deal with float truncation in many places. I'd say
avoid trying to be too clever on application programmers' behalf. The
automatic rad/deg conversion is useful (particularly coming from the world
of Unity where they use a mixture of the two in the API), but maybe
introduce another convertible type for this extra functionality?

**Comment by mosra** [comment]
I'm working on animation support right now (#191) and just realized that wraparound would actively harm some currently valid use cases. For example, imagine you have an object that you want to rotate five times. With the current Deg/Rad API you'd just have two keyframes, one specifying `0.0_degf` rotation and the other a `1800.0_degf` rotation. Linearly interpolating between these two will then produce the correct animation. With wraparound enabled, both keyframes would end up being `0.0_degf` and one would need to manually add a lot of artificial non-trivial in-between keyframes to convince the object to rotate.

> but maybe another convertible type for this extra functionality?

Very good point. Thinking about this, what about simply using [Complex](http://doc.magnum.graphics/magnum/classMagnum_1_1Math_1_1Complex.html) for this? If you need wraparound, it's probably because you're later feeding the angle to some trig function anyway so you would need to calculate sin/cos one way or the other so why not store the value like that already? And multiplying normalized complex numbers (that are representing rotation) wraps around implicitly.

**Comment by mosra** [comment]
Based on the discussion above, I'm closing this as "wontfix" -- there are simply too many disadvantages for implementing such feature. For a wraparound feature, please consider using the `Complex` data type, as I mentioned above.
