### ISSUE TITLE
Quaternion fromMatrix

### ISSUE THREAD

**Issue by tdejager** [mosra/magnum#295]
Hi!

I was just looking at the `fromMatrix` code in the quaternion class. This was the code I've found:

```cpp
template<class T> Quaternion<T> quaternionFromMatrix(const Matrix3x3<T>& m) {
    const Vector<3, T> diagonal = m.diagonal();
    const T trace = diagonal.sum();

    /* Diagonal is positive */
    if(trace > T(0)) {
        const T s = std::sqrt(trace + T(1));
        const T t = T(0.5)/s;
        return {Vector3<T>(m[1][2] - m[2][1],
                           m[2][0] - m[0][2],
                           m[0][1] - m[1][0])*t, s*T(0.5)};
    }

    /* Diagonal is negative */
    std::size_t i = 0;
    if(diagonal[1] > diagonal[0]) i = 1;
    if(diagonal[2] > diagonal[i]) i = 2;

    const std::size_t j = (i + 1) % 3;
    const std::size_t k = (i + 2) % 3;

    const T s = std::sqrt(diagonal[i] - diagonal[j] - diagonal[k] + T(1));
    const T t = (s == T(0) ? T(0) : T(0.5)/s);

    Vector3<T> vec;
    vec[i] = s*T(0.5);
    vec[j] = (m[i][j] + m[j][i])*t;
    vec[k] = (m[i][k] + m[k][i])*t;

return {vec, (m[j][k] - m[k][j])*t};
```

My question is if this method handles some corner cases as described here: http://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToQuaternion/

Or would this need to be improved?

I've been bitten by these before, especially for small rotations.

**Comment by mosra** [comment]
Hi!

I wrote this code hmm... nearly six years ago, so please forgive me if I get something wrong ;) If I remember correctly, I based the code on this very page, but instead of having three different `else` clauses, I dynamically calculated the `j` and `k` indices and then based the rest on these instead.

The corresponding test is here: https://github.com/mosra/magnum/blob/d6f91d986c8b305a0ce37b66434582503ae0c47f/src/Magnum/Math/Test/QuaternionTest.cpp#L490-L532 and if I did it correctly back then, it should be testing for all cases described on the page you linked.

> I've been bitten by these before, especially for small rotations.

Was it with Magnum or something else? I don't remember any problem or issue being reported in relation to this particular conversion, and the code is basically unchanged since the initial implementation in da93b2ad6aafe3237c402b29fa889e61129eeab6 (Mar 2013). That said, if you know about a corner case it *doesn't* handle well, please tell me — the most ideal would of course be submiting a PR that extends the test with given corner case and fixes the code to handle it ;)

**Comment by tdejager** [comment]
Hi Mosra, thanks for the quick response.

Thanks, I'll have a look, and no it was not in magnum. I was just using magnum for another project and was looking at the quaternion code. So if I find the orientation that was causing me problems I will test this with magnum and have a look at the results, if there is a problem I will submit a PR. For now, I will close this issue!

**Comment by mosra** [comment]
Ah, cool then :) Yes please, if you see something suspicious there, submit a report.
