### ISSUE TITLE
Text rendering glyph clipping

### ISSUE THREAD

**Issue by franko** [mosra/magnum#313]
Rendering fonts using approach from text rendering example produce sometimes glyphs that appears clipped on the left side:

![image](https://user-images.githubusercontent.com/433545/52450846-0fd30d80-2b3d-11e9-8694-fc71513d4e98.png)

Using essentially (just extract from the actual code):

```c++
// --------------------- Variables
PluginManager::Manager<Text::AbstractFont> _manager;
Containers::Pointer<Text::AbstractFont> _font;
Text::DistanceFieldGlyphCache _cache;
Shaders::DistanceFieldVector2D _textShader;
Matrix3 _textViewportScaling;
Containers::Pointer<Text::Renderer2D> _text;

// --------------------- App initialization
/* Load FreeTypeFont plugin */
_font = _manager.loadAndInstantiate("FreeTypeFont");
if(!_font) std::exit(1);

/* Open the font and fill glyph cache */
Utility::Resource rs("fonts");
if(!_font->openSingleData(rs.getRaw("DejaVuSans.ttf"), 110.0f)) {
    Error() << "Cannot open font file";
    std::exit(1);
}

_font->fillGlyphCache(_cache, "xyzXYZ0123456789.eE+- ");

GL::Renderer::enable(GL::Renderer::Feature::DepthTest);
GL::Renderer::enable(GL::Renderer::Feature::Blending);
GL::Renderer::setBlendFunction(GL::Renderer::BlendFunction::SourceAlpha, GL::Renderer::BlendFunction::OneMinusSourceAlpha);
GL::Renderer::setBlendEquation(GL::Renderer::BlendEquation::Add, GL::Renderer::BlendEquation::Add);

_text = Containers::Pointer<Text::Renderer2D>{new Text::Renderer2D(*_font, _cache, 0.02f, Text::Alignment::MiddleRight)};
_text->reserve(12, GL::BufferUsage::DynamicDraw, GL::BufferUsage::StaticDraw);
_text>render("-0.2");

_textViewportScaling = Matrix3::scaling(Vector2::yScale(Vector2(GL::defaultFramebuffer.viewport().size()).aspectRatio()));

// --------------------- Drawing
_textShader.bindVectorTexture(_cache.texture());
_textShader.setColor(Color3{0.3f})
    .setSmoothness(0.075f);

GL::defaultFramebuffer.clear(GL::FramebufferClear::Depth).clearColor(Color4{1.0f});

_textShader.setTransformationProjectionMatrix(Matrix3::translation({0.0, 0.0}) * _textViewportScaling);
_text->mesh().draw(_textShader);
}
```

**Comment by mosra** [comment]
As we talked on the chat: can you try using the normal `GlyphCache` instead of the `DistanceFieldGlyphCache`? Since you do not need arbitrary text scaling, it will have much crisper look. The only difference is in the amount of constructor parameters, you need just the first.

Besides that, the `0.02f` passed to font size looks quite suspicious and I think that's the core of the problem. You're loading the font in a size `110.0f` but then scaling it to 0.02% of its size. Large glyphs usually have quite a different metric than the same glyphs at much smaller sizes, causing such clipping. You could try using e.g. `11.0f` and `0.2f`, if that improves stuff. Even if it does, I'd still recommend switching to the non-distance-field-based glyph cache.

**Comment by franko** [comment]
Ok, here my findings when following your suggestions.

With the GlyphCache instead of DistanceFieldGlyphCache the fonts looks bad:

![image](https://user-images.githubusercontent.com/433545/52488549-5c136180-2bc0-11e9-9ab5-9e68863b42a7.png)

Otherwise, if I keep using DistanceFieldGlyphCache, I found out that:

using 11.0f in

```c++
_font->openSingleData(rs.getRaw("DejaVuSans.ttf"), 11.0f)
```

and 0.2f in the call to `Text::Renderer2D` does not work at all. No text is visible at all but I may be doing something wrong.

Otherwise I found out that it works better by using 

```c++
_font->openSingleData(rs.getRaw("DejaVuSans.ttf"), 110.0f)
```

with 110 or more. In turns the actual size of the font on the screen depends **only** on the size you provide to the `Text::Renderer2D`.

The values I am using come from the Text renderer examples except I use 0.02f to draw small fonts instead of 0.075 used in the example.

Otherwise I made my repository public:

https://github.com/franko/magnum-function-plot

So you can easily see and test if needed.

**Comment by mosra** [comment]
> With the GlyphCache instead of DistanceFieldGlyphCache the fonts looks bad:

> In turns the actual size of the font on the screen depends **only** on the size you provide to the `Text::Renderer2D`.

Let me explain, there are two different things:

- The size at which the text glyphs are prerendered and stored in a texture (which is the `110.0f`). That's in pixels (or maybe in some weird `pt`s, where one point is 2.54 pixel I think, not 100% sure now).
- The size at which the text is actually drawn on screen. That's relative to projection size (whatever you define for your camera matrix), and then the projection size relative to window size defines how many actual screen pixels is each glyph.

Then, the artifacts:

- In case of distance field rendering, a big difference between these two (a glyph that was 100 pixels high at first is rendered 10 pixels high) would not cause serious artifacts as the glyph image gets scaled correctly, but may cause the clipping you see above due to various imprecisions on the way. The look can be further tuned by the radius parameter, which is 22 in your case (passed to the [DistanceFieldGlyphCache(const Vector2i&, const Vector2i&, UnsignedInt)](https://doc.magnum.graphics/magnum/classMagnum_1_1Text_1_1DistanceFieldGlyphCache.html#a280c9b4934da5b98f5204181eafbe94f) constructor), and then the [Shaders::DistanceFieldVector::setSmoothness()](https://doc.magnum.graphics/magnum/classMagnum_1_1Shaders_1_1DistanceFieldVector.html#a5aa7fe5ef127755b16f84273522a5053) parameter. You can try decreasing the radius and then increasing the smoothness to see how it affects the rendering.
- In case of the normal glyph cache, a big difference between these two causes what you see above -- it tries to cram a 100 pixel big glyph into a space of 10 pixels, so it just select a bunch of original random pixels, causing the blocky look. In this case the goal is to ideally have the rendered glyph pixels match 1:1 the screen pixels. Try lowering the first value to e.g. 36.

Hopefully this clears things up a bit! :slightly_smiling_face: There is many parameters that go in the equation so it might be hard to achieve the desired look at first.

**Comment by franko** [comment]
Thank you for the clarifications. I confirm that the radius parameter in DistanceFieldGlyphCache helps. I got good results with radius to 12 and using an higher smoothness.

The other approach you suggested, using the GlyphCache also seems to work but you have to "guess" by trials the glyph size. As I may finally end up using different font size I think I will stay with the distance field.

So, you may close this issue if you want and thanks again for your help! :-)

**Comment by mosra** [comment]
The difference in crispness and rendering quality between normal and distance field glyph cache gets much more visible when using complex writing systems (chinese etc.). With plain latin alphabet the difference is usually minimal, unless you to really really tiny sizes.

Okay then, closing :)
