### ISSUE TITLE
It finds /usr/local/lib/libGLESv2.so and then doesn't use it

### ISSUE THREAD

**Issue by yurivict** [mosra/magnum#319]
configure says
```
-- Found OpenGLES2: /usr/local/lib/libGLESv2.so  
```
but no binaries then are linked with it.

**Comment by yurivict** [comment]
Same with these:
```
-- Found X11: /usr/local/lib/libX11.so
-- Found SDL2: /usr/local/lib/libSDL2.so  
-- Found EGL: /usr/local/lib/libEGL.so  
```

**Comment by yurivict** [comment]
options:
```
CMAKE_ON=       BUILD_SHARED_LIBS \
                TARGET_GLES WITH_GL_INFO WITH_IMAGECONVERTER WITH_ANYIMAGEIMPORTER WITH_ANYAUDIOIMPORTER \
                WITH_ANYIMAGECONVERTER WITH_ANYSCENEIMPORTER WITH_WAVAUDIOIMPORTER WITH_MAGNUMFONT WITH_OBJIMPORTER \
                WITH_SHAPES WITH_SHADERS WITH_TEXT WITH_TEXTURETOOLS WITH_TRADE \
                WITH_GL WITH_PRIMITIVES WITH_EGLCONTEXT WITH_GLXAPPLICATION WITH_WINDOWLESSGLXAPPLICATION \
                WITH_GLXCONTEXT WITH_XEGLAPPLICATION WITH_GLFWAPPLICATION WITH_SDL2APPLICATION
```

**Comment by mosra** [comment]
It's ... complicated, because OpenGL is complicated. The `libMagnumGL.so` is linking to `libGLESv2`, but loads the majority of its symbols through `glXGetProcAddress()` (from X11), `eglGetProcAddress()` (from EGL) etc. depending on what platform are you on, what Application library you use and what CMake options are enabled. And since the Application (e.g. `libMagnumSdl2Application.a`, using SDL2), is a static library (as you discovered in #318), there's no visible connection between these two, until you link it all together to a final executable. Nevertheless, CMake still needs to find them to be able to use the corresponding `#include`s.

Does this answer your question? :)

**Comment by yurivict** [comment]
> And since the Application (e.g. libMagnumSdl2Application.a, using SDL2), is a static library (as you discovered in #318), there's no visible connection between these two, until you link it all together to a final executable. Nevertheless, CMake still needs to find them to be able to use the corresponding #includes.

This is why static libraries are evil, they hide dependencies like this.

Why not reconsider and make all libraries shared, regardless of size?

**Comment by yurivict** [comment]
See, static libs make packaging complicated.
If some shared lib is needed, but this isn't obvious, later this will be forgotten about, and it will be "Oops!" need to add this lib to ```LIB_DEPENDS```, and this will happen many times, too. It's just an unnecessary complication, IMO.

**Comment by mosra** [comment]
> See, static libs make packaging complicated.

I'm afraid I have to disagree ;) Over the last decade, Magnum and related libs got packaged in almost a dozen different packaging systems and this was never a problem. We spent more time on packaging systems that are a particularly complex beast, such as the one from Debian, but from experience that pointed rather at the design of the packaging system than at the design of this library.

What platform are you packaging for? I'm happy to answer questions and help you with the process.

**Comment by mosra** [comment]
@yurivict is there anything left to be done for this? Otherwise I'll close the issue.
