### ISSUE TITLE
building a minimal project on OS X with cmake

### ISSUE THREAD

**Issue by andreihu** [mosra/magnum#329]
Hello Folks,

 I am trying to create a minimal test application using magnum on OSX. At first i tried to use a custom scons-based build system, where i was able to build a binary, but of course this was a matchsticks-and-glue solution, so i decided to transition to cmake (for which i have no experience yet).

I have came up with the following cmake file:
`
cmake_minimum_required(VERSION 3.1)

project(graph-presenter CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(Boost REQUIRED COMPONENTS graph)
find_package(Magnum REQUIRED GL Shaders Sdl2Application)

set_directory_properties(PROPERTIES CORRADE_USE_PEDANTIC_FLAGS ON)

add_executable(graph-presenter main.cpp)
target_link_libraries(graph-presenter Boost::graph Magnum::Magnum Magnum::Application Magnum::GL Magnum::Shaders)
`

Unfortunately i am receiving an error message during build:
`
[cmake] CMake Error at CMakeLists.txt:13 (add_executable):
[cmake]   Target "graph-presenter" links to target "SDL2::SDL2" but the target was
[cmake]   not found.  Perhaps a find_package() call is missing for an IMPORTED
[cmake]   target, or an ALIAS target is missing?
`

I am using MacOS 10.14, magnum and SDL were installed via homebrew.

Any help/advice is greatly appreciated.
Andras

**Comment by mosra** [comment]
Hi!

This needs the `FindSDL2.cmake` from the `modules/` directory to be present, that one defines the `SDL2::SDL2` target correctly. The SDL2's own Find module for some reason doesn't and that's why the stuff breaks like this. Sorry about that, this error is one of the *bad* ones.

The easiest way to get up & running is by picking up the stuff from the [bootstrap project](https://github.com/mosra/magnum-bootstrap/tree/base) -- in particular the whole `modules/` directory and referencing it from CMake like this:

```cmake
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${PROJECT_SOURCE_DIR}/modules/")
```

**Comment by andreihu** [comment]
Hi!

 Thanks for the ultra-fast response. Your advice was correct, now i can build the project properly.

Have a nice day
 Andras

**Comment by mosra** [comment]
Yay! :) Have a nice day too.
