### ISSUE TITLE
Mesh Rectangle failing

### ISSUE THREAD

**Issue by sariug** [mosra/magnum#334]
Hello,

I am new in magnum graphics, as well as computational graphics. I am trying to create a **Rectangle Prism** mesh using indices however, not super working. ( trying to put 12 lines and thats it.) Can someone able to see the problem  ?

```cpp
GL::Mesh Rectengular(){
    Vector3 Position[8] = {
        {0.0f, 0.0f, 0.0f}, {1.0f, 0.0f, 0.0f},
        {1.0f, 1.0f, 0.0f}, {0.0f, 1.0f, 0.0f},
        {0.0f, 0.0f, 1.0f}, {1.0f, 0.0f, 1.0f},
        {1.0f, 1.0f, 1.0f}, {0.0f, 1.0f, 1.0f},
    };

    GL::Buffer vertexBuffer;
    vertexBuffer.setData(Position, GL::BufferUsage::StaticDraw);

    /* Fill index buffer with index data */
    UnsignedByte indices[]{
    // Front
       0, 1,
       1, 2,
       2, 3,
       3, 0,
    // Back
       4, 5,
       5, 6,
       6, 7,
       7, 4,
    // Connect with sides
       0, 4,
       1, 5,
       2, 6,
       3, 7
    };

    GL::Buffer indexBuffer;
    indexBuffer.setData(indices, GL::BufferUsage::StaticDraw);

    GL::Mesh _rect{NoCreate};
    _rect = GL::Mesh{};
    _rect.setPrimitive(MeshPrimitive::Lines)
        .addVertexBuffer(vertexBuffer, 0, MyShader::Position{})
        .setIndexBuffer(indexBuffer, 0, GL::MeshIndexType::UnsignedByte, 176, 229)
        .setCount(8);
    return _rect;
}
```

From an angle:
![image](https://user-images.githubusercontent.com/14132181/56081292-ef108800-5e0b-11e9-9a8e-556c0c1d24c3.png)

My expectation is something like :
![image](https://user-images.githubusercontent.com/14132181/56081351-98f01480-5e0c-11e9-9972-9e9cace29cfc.png)

**Comment by mosra** [comment]
Hi!

*(Edited your post slightly to make the code blocks more readable, hope that's okay.)*

The code is almost correct, I see only three small problems there:

- [Mesh::setCount()](https://doc.magnum.graphics/magnum/classMagnum_1_1GL_1_1Mesh.html#a48dec084ecf8ce1a152889e7e4175d86) takes number of indices if the mesh is indexed and number of vertices if the mesh is non-indexed. So in your case, that'll be `setCount(24)` instead of 8. Drawing just 8 of them is just one rectangle, which is what you saw.
- The `GL::Buffer` instances are going out of scope when the function exits, which means the GPU memory is freed and the mesh then references invalid memory. This might accidentally work in some cases (it apparently did in yours), but will fail spectacularly in others. One options is to return them together with the mesh (so the function would return e.g. `std::tuple<GL::Mesh, GL::Buffer, GL::Buffer>`) and then ensure they stay alive as long as the mesh instance. But that's quite verbose and probably not needed in this particular case, the other option is to transfer their ownership to the mesh by `std::move()`ing them inside [as described here](https://doc.magnum.graphics/magnum/classMagnum_1_1GL_1_1Mesh.html#GL-Mesh-buffer-ownership).
- and a rather minor thing, the last two parameters of [Mesh::setIndexBuffer()](https://doc.magnum.graphics/magnum/classMagnum_1_1GL_1_1Mesh.html#ad0f46d645633363d887274735b39b76f) are to say what range the index array spans, which, in your case would be `0, 7` instead of the (rather random) `176, 229`. That said, the last two parameters are completely optional -- it's meant to be an optimization so the GPU knows what memory to fetch when you're for example rendering just a subset of a large mesh -- but they probably get completely ignored by todays GPUs anyway, so there's no need to bother.

So, finally, the working code is:

```cpp
    GL::Mesh rect;
    rect.setPrimitive(MeshPrimitive::Lines)
        .addVertexBuffer(std::move(vertexBuffer), 0, MyShader::Position{})
        .setIndexBuffer(std::move(indexBuffer), 0, GL::MeshIndexType::UnsignedByte)
        .setCount(24);
    return rect;
}
```

**Comment by sariug** [comment]
Worked like magic ! 

Also carried it to a RectPrism class to keep everything in scope ! 

Thanks !
