### ISSUE TITLE
Matrix4::perspectiveProjection result is different from GLM, etc

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [mosra/magnum#336]
Matrix4::perspectiveProjection gives a different result from GLM, and typical GL textbooks. Why is that?

Magnum:
```
    const auto fov = 45.0_degf;
    const Vector2i winsize{1280, 720};
    const float near = 0.1F;
    const float far = 100.0F;


    auto proj_mat_test = Matrix4::perspectiveProjection(
        fov,
        Vector2{winsize}.aspectRatio(),
        near,
        far
    );

    dbgprintmat("proj_mat", proj_mat_test);
```
which prints out:
```
proj_mat
2.41421 0 0 0
0 4.29193 0 0
0 0 -1.002 -0.2002
0 0 -1 0
```

GLM:
```
    const auto fov = glm::radians(45.0f);
    glm::vec2 winsize(1280, 720);
    float _near = 0.1F;
    float _far = 100.0F;

    auto proj_mat = glm::perspective(
        fov,
        (float)winsize.x / (float)winsize.y,
        _near,
        _far
    );

    dbgprintmat("Glm proj mat", proj_mat)
```
which prints out: 
*also same result as manual calculation
```
Glm proj mat
1.358 0 0 0
0 2.41421 0 0
0 0 -1.002 -0.2002
0 0 -1 0
```

```
template <typename T>
void dbgprintmat(const char* msg, T mat)
{
    COUT << msg << ENDL;

    for (auto ri = 0; ri <= 3; ri++)
    {
        COUT << mat[0][ri] << " " << mat[1][ri] << " " << mat[2][ri] << " " << mat[3][ri] << ENDL;
    }
}

```

**Comment by mosra** [comment]
Hi!

[Matrix4::perspectiveProjection()](https://doc.magnum.graphics/magnum/classMagnum_1_1Math_1_1Matrix4.html#a6475b3ef155c9142b890c8133504ae9b) states that the FoV is horizontal, while GLM [has it vertical](https://glm.g-truc.net/0.9.4/api/a00151.html#ga283629a5ac7fb9037795435daf22560f). Few tips that might be useful:

- For most math APIs (and this one as well), there's a math equation reflecting what the code does. That's the "ground truth" and that's how the API is expected to behave. I can't ensure that the results are consistent with other libraries or textbooks because with some APIs there's more than one way how the inputs can be interpreted. (If I remember correctly, the equation used there is taken from some textbook as well, however I can't tell you which one, it's quite a long time since ;))
- You can print all Magnum math types (and most enums, or any container of these) using `Debug{} << mat;` -- you shouldn't be forced to write your own debug printers ;) [Full docs here.](https://doc.magnum.graphics/corrade/classCorrade_1_1Utility_1_1Debug.html)
- In case you want to keep using GLM, you might want to check out [GlmIntegration](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1GlmIntegration.html) providing explicit conversion between Magnum types and GLM types (and also making it possible to print GLM types with `Debug`).

**Comment by UNDEFINED-BEHAVIOR** [comment]
Oh, I see..
```Debug{} << mat;```
Thanks for the *pointers!
