### ISSUE TITLE
Text influence on objects position. Creating objects at runtime

### ISSUE THREAD

**Issue by Selot** [mosra/magnum#353]
Hello!
I have a problem using text. When a text and objects (red points) is created from opengl thread - all fine.
![creating with init context](https://user-images.githubusercontent.com/20381903/60755953-fa84e100-9fff-11e9-93a8-3d3ceaab712a.png)

If creating objects at runtime from GUI thread (I'm using Qt widgets), then they offset own positions with text length (or even with `Text::Alignment`).
![create objs at runtime](https://user-images.githubusercontent.com/20381903/60755956-07a1d000-a000-11e9-8e8e-1b5755b37916.png)

Is it bug or feature? :) What is the right way to create objects at runtime with text?

**Comment by mosra** [comment]
Hi, sorry, I don't understand your question.

- what are the objects? objects in a scene graph? directly rendered meshes?
- what's their relation? are they parented to the text or vice versa? are properties of the text used to calculate their position?
- what do you mean by "GUI thread"? are you using multithreading?

**Comment by Selot** [comment]
> what are the objects? objects in a scene graph? directly rendered meshes?

Objects (i.e. RedPoints) in a scene graph. Scene graph look like:

```
Scene
  |---cameraObj
  |       |---Camera
          |---group1
          |       |---RedPoint1
          |       |---....
          |       |---RedPointN
          |
          |---group2
          |       |---Text
          |
```

> what's their relation? are they parented to the text or vice versa? are properties of the text used to calculate their position?

RedPoints and Text are independent of each other.

> what do you mean by "GUI thread"? are you using multithreading?

Hmm, no. But how I understend Qt using own thread for handle mouse/keyboard input. And member-function `QOpenGLWidget::paintGL` called from another thread automaticlly. Result 
is different when I try create "RedPoint" from `paintGL` (like 1st screen) function and when i try create by `keyPressEvent` (like 2nd screen) . Sorry if i'm wrong.

**Comment by mosra** [comment]
> Ok, it's just async.

If I remember correctly, in the main (GUI thread) Qt has an event loop (started by `QApplication::exec()`) and only calls `keyPressEvent()` at a different point than `paintGL()` in that loop, without doing any parallel / threading stuff. Magnum's own Application implementations do the same.

> But result is different when I try create "RedPoint" from `paintGL()` (like 1st screen) function and when i try create by `keyPressEvent()` (like 2nd screen) .

Ah -- that could be because `keyPressEvent()` might not have the same GL context bound as `paintGL()`. I vaguely remember there were some guidelines saying you should be doing everything GL-related only from `paintGL()` but I don't remember anymore. Looking at https://doc.qt.io/qt-5/qopenglwidget.html#paintGL, it seems you might only need to additionally call `makeCurrent()` in `keyPressEvent()` (and together with that Magnum's own `resetState()` functions like you already do in `paintGL()`), but I am not 100% sure on that -- you might need to dive deeper into the Qt documentation to understand what's actually going on underneath.

Hope this helps at least a bit -- I'm only guessing here :)

**Comment by Selot** [comment]
Thanks a lot! Adding `makeCurrent()` and `resetState()` to `keyPressEvent()` - all fine :)

**Comment by mosra** [comment]
Great :)
