### ISSUE TITLE
Corrade VS2019 support

### ISSUE THREAD

**Issue by hsdk123** [mosra/magnum#354]
Magnum doesn't configure on CMake properly for VS2019 with error:
```
To use Corrade with MSVC 2019, build it with MSVC2019_COMPATIBILITY enabled
```
Even if I do define `MSVC2019_COMPATIBILITY`, configure doesn't work.
If I define `CORRADE_MSVC2019_COMPATIBILITY`, configure works.

**Comment by mosra** [comment]
Hi! 

This is most probably due to an outdated `FindCorrade.cmake`. Assuming this happens while configuring your own project (and not while building Magnum itself, there it [seems to be okay](https://magnum.graphics/build-status/)), can you put [a fresh copy of FindCorrade.cmake](https://github.com/mosra/corrade/blob/master/modules/FindCorrade.cmake) into your project's module directory and try again?

I'm aware that this problem happens with projects from the `magnum-bootstrap` repository, still need to update that one (sorry about that if that's the case).

**Comment by hsdk123** [comment]
Hey! Yup, I was building from the `magnum-bootstrap` repo. Seems to work well with the new FindCorrade.cmake. 

I was also just in the process of evaluating whether to shift my team to using Magnum. It's great to see such fast responses!

**Comment by mosra** [comment]
As of mosra/magnum-bootstrap@0b384ce029e51d81b3d4c678621140358a29cd8d (and related changes in other repos), the magnum-bootstrap repo is *finally* updated for MSVC 2019 compatibility.
