### ISSUE TITLE
VS2019 codepage warnings

### ISSUE THREAD

**Issue by hsdk123** [mosra/magnum#355]
I'm receiving the following warnings for practically all the files included
```
top\magnum-bootstrap-base\corrade\src\Corrade/Containers/ArrayView.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
5>  C:\Users\hsdk.bd\Desktop\magnum-bootstrap-base\corrade\src\Corrade/Utility/Debug.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
5>  C:\Users\hsdk.bd\Desktop\magnum-bootstrap-base\corrade\src\Corrade/Containers/StaticArray.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
```
It would be great to have the files saved in Unicode format to prevent these warnings.

**Comment by mosra** [comment]
> It would be great to have the files saved in Unicode format to prevent these warnings.

Sorry, but the files *are* in UTF-8 and were so since *ever*. Not sure why not on your machine, to be honest I never saw such a warnings being reported by MSVC :) Is there a possibility that your clone / code download has the files broken somehow? I'm explicitly putting at least one UTF-8 character into every file copyright header (the `©` character) in order to avoid the files being accidentally misinterpreted under a different encoding.

**Comment by hsdk123** [comment]
Thanks for the quick response! My team's currently working with non-english OS machines, and the default codepage thus is probably the reason. 

However, the warning does go away if the files are saved with [UTF-8 with BOM](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4819?view=vs-2019), thus I'd like to propose the files be saved in that format to remove warnings.

**Comment by mosra** [comment]
That would unfortunately cause serious problems on [all other platforms](https://utf8everywhere.org/#faq.boms) :( While not using Windows often myself, I have several people using it (and MSVC) with non-english locales (German, French, Russian) and nobody experienced this problem yet. Are *your* source files UTF-8 as well? Or in a local codepage?

Found this alternative solution: https://stackoverflow.com/a/37872393 -- basically if your source files are UTF-8 as well, specifying `/utf8` (via `CMAKE_CXX_FLAGS` for example) should make it do the right thing without requiring any BOMs. Can you try that?

**Comment by hsdk123** [comment]
I'm currently just tinkering with the base bootstrap, and haven't added any files. I'm trying to set `CMAKE_CXX_FLAGS` in cmake-gui (type: string, value: "/utf8"), but each time I add the entry and configure, the setting doesn't show up. Am I doing something wrong?

**Comment by mosra** [comment]
This variable is there already if you tick the "Show Advanced" box, append to it. I guess it doesn't allow you to add a new one with the same name (or it maybe gets hidden since it's one of the Advanced ones).

Alternatively, you could set this inside the project's `CMakeLists.txt` like this -- do that right below the `project()` command:

```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /utf-8")
```

**Comment by hsdk123** [comment]
`/utf-8` does the job! My output messages are finally clearer, thanks! (might be useful to add this one to the docs)

**Comment by mosra** [comment]
Glad to hear that :) Will do!

**Comment by mosra** [comment]
Phew, finally I'm able to catch up on all these -- documentation added in 0fac99149d265315fa2a71784e9d179242eb990b ([live version](https://doc.magnum.graphics/magnum/platforms-windows.html#platforms-windows-troubleshooting)).
