### ISSUE TITLE
AnyImageImporter linking issue on mac os

### ISSUE THREAD

**Issue by AboudFayad** [mosra/magnum#358]
I am trying to use AnyImageImporter plugin in my magnum application, but when I try to build it on my mac, I get the following:

```
ld: can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file '/usr/local/lib/magnum/importers/AnyImageImporter.so' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [mold] Error 1
make[1]: *** [CMakeFiles/mold.dir/all] Error 2
make: *** [all] Error 2
```
This problem does not present on windows.

**Comment by mosra** [comment]
That happens because the dynamic plugins are not meant to be linked -- instead the plugin manager is supposed to find them on the filesystem and load dynamically at runtime. If you *really* want to have the plugins linked at build time, I suggest to use static plugins instead. Coincidentally I was just explaining that in #357, see my comment there for details. (The docs need to explain this better, it's on my TODO list.)

By the way, for general questions you're always welcome on the Gitter channel -- https://gitter.im/mosra/magnum. There's always someone around happy to help and the response time is generally faster than when opening an issue. Simply log in with your GitHub account :)

**Comment by mosra** [comment]
Closing in favor of #357.
