### ISSUE TITLE
Application do not call drawEvent every frame.

### ISSUE THREAD

**Issue by janbajana** [mosra/magnum#391]
I have found an issue with `drawEvent()`.
Experienced it on Android and desktop SDL application lifecycle from `Magnum::Application` implementation.

`drawEvent()` is called only ones so the scene is rendered only once.
Do I just miss some configuration?

For Sdl2Application I just commented out the bitwise operation from
`858: // _flags &= ~Flag::Redraw;` and all started to work.

Here is my referral code. 
https://github.com/janbajana/magnum-bootstrap-android/blob/master/src/MyApplication.cpp

**Comment by mosra** [comment]
This is done intentionally by design in all Application classes, since not every app using a GPU needs to draw at 60 Hz (for example, most of the examples don't need to redraw that often, [magnum-player](https://magnum.graphics/showcase/player/) that just shows a static scene doesn't need to either, on WebGL you also don't want to be using 100% CPU all the time etc.). Yes, I admit it's different from about every other graphic lib out there, but I like things to be power-efficient by default.

To tell the application to redraw as fast as possible, call [redraw()](https://doc.magnum.graphics/magnum/classMagnum_1_1Platform_1_1Sdl2Application.html#a07b8148f0f212659259d060c7b6ad2bc) at the end of your `drawEvent()`. The [setSwapInterval()](https://doc.magnum.graphics/magnum/classMagnum_1_1Platform_1_1Sdl2Application.html#a745b3b3793fb1a65e30d1fce72c0625e) and [setMinimalLoopPeriod()](https://doc.magnum.graphics/magnum/classMagnum_1_1Platform_1_1Sdl2Application.html#a296b443b1cfb30460417f0e897042764) methods might be of interest, too.

- - -

Btw., for general questions / and issues such as this one, you're most welcome in the [Gitter channel](https://gitter.im/mosra/magnum) -- there you'll usually get a reply very quickly and it's also less formal :) Simply log in with your GitHub account.

**Comment by janbajana** [comment]
Ok, I see. This is good. redraw() worked for me. 
Yes, setSwapInterval() is useful as well. For my testing purposes, I need to update with VSync.

I have to find time to read Magnum documentation deeper to do not ask simple questions like this :).
I will use Gitter as well.

Thank you for your answer.
