### ISSUE TITLE
EmscriptenApplication: mouse position never changes if DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR is enabled

### ISSUE THREAD

**Issue by bowling-allie** [mosra/magnum#408]
This took awhile. oops
I've been hanging onto this issue for a while because its platform specific, emscripten is hard to debug, etc.

The symptom was that I could not interact with imgui at all.

_Sdl2Application on emscripten doesn't have this bug_, it's just EmscriptenApplication.
I was originally going to make an issue with the integration repo, because I found https://github.com/mosra/magnum-integration/commit/84fa6d84f5ac5bdbbcfd829e738e7fa6859d1b36, and assumed that was the issue, _but_ long story short I found out it wasn't. And reverting that commit did not fix the bug.

So...

I finally had the great idea to just check the mouse coordiantes being given to me by EmscriptenApplication and,,.,,..

they were always (0, 72) or something like that.

so I looked deep within `EmscriptenApplication.cpp` to find:
https://github.com/mosra/magnum/blob/34261840bc6b2c3e1bf3899605bb638ff687a0ff/src/Magnum/Platform/EmscriptenApplication.cpp#L499-L506

This comment made me realize I had turned that on some time ago. So I turned it off and it works, I'm not sure why.

**Comment by mosra** [comment]
Hi, thanks a lot for discovering this!

Turns out it was due to `canvasX`/`canvasY` properties not being populated when `DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR ` is enabled, and unfortunately this was not mentioned anywhere in the docs, only in the corresponding header file so I completely missed that (and didn't test properly). Additionally this flag seems to be enabled by default since https://github.com/emscripten-core/emscripten/pull/9946, so you discovered this at the *right* time :)

Should be fixed in e603771cef3b72547a71709243b492172ac8bb8b, I tested move, click and wheel events and all seem to work. Please let me know if there's still something off.
