### ISSUE TITLE
Periodic linking error when building in docker with emscripten

### ISSUE THREAD

**Issue by celentes** [mosra/magnum#413]
I periodically (less than 5% of the time) get the following error when building magnum:

```
-- The CXX compiler identification is Clang 6.0.1
-- Check for working CXX compiler: /emsdk_portable/emscripten/tag-1.39.4/em++
-- Check for working CXX compiler: /emsdk_portable/emscripten/tag-1.39.4/em++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Corrade: /usr/lib/emscripten/system/include  found components:  Containers rc Utility
-- Found OpenGLES3: GL
-- LIB_SUFFIX variable is not defined. It will be autodetected now.
-- You can set it manually with -DLIB_SUFFIX=<value> (64 for example)
-- LIB_SUFFIX autodetected as '', libraries will be installed into /usr/lib/emscripten/system/lib
-- Found SDL2: /emsdk_portable/emscripten/tag-1.39.4/system/include/SDL
-- Found Corrade: /usr/lib/emscripten/system/include  found components:  Containers rc Utility Main TestSuite
-- Found Corrade: /usr/lib/emscripten/system/include  found components:  Containers rc Utility PluginManager
-- Configuring done
-- Generating done
-- Build files have been written to: /buildroot/magnum/build
[73/164] Linking CXX static library Release/lib/MagnumSdl2Application.bc
FAILED: Release/lib/MagnumSdl2Application.bc
: && /opt/cmake/bin/cmake -E remove Release/lib/MagnumSdl2Application.bc && emsdk_portable/emscripten/tag-1.39.4/emar qc Release/lib/MagnumSdl2Application.bc  src/Magnum/Platform/CMakeFiles/MagnumPlatformObjects.dir/Implementation/DpiScaling.cpp.o src/Magnum/Platform/CMakeFiles/MagnumSdl2Application.dir/Sdl2Application.cpp.o && /emsdk_portable/emscripten/tag-1.39.4/emranlib Release/lib/MagnumSdl2Application.bc && :
/emsdk_portable/clang/tag-e1.39.4/build_tag-e1.39.4_64/bin/llvm-ar: /buildroot/magnum/build/src/Magnum/Platform/CMakeFiles/MagnumPlatformObjects.dir/Implementation/DpiScaling_fe5a6db6.cpp.o: No such file or directory.

```
I am building it in docker, to isolate all the external factors that might pollute the local installation.
Link to docker setup: https://github.com/celentes/magnum-docker.

As far as I understand, DpiScaling_fe5a6db6.cpp.o is a temporary output file, then cmake is renaming it and cutting the generated suffix. Somehow emar periodically gets that as input as opposed to correct end file. I have caught this error with both ninja and make when multithreaded, at the moment running single threaded make on repeat to check if it will reproduce.

**Comment by mosra** [comment]
Hi!

apologies if I sound harsh, but today is full of terrible insane issues from hell, and this one seems to be no exception 😆

Looking into `build.ninja`, adding hashes to filenames isn't CMake's business at all (and it can be seen from the command line -- it expects just plain DpiScaling.cpp.o). I did some further digging and it seems Emscripten is to blame, though I have no idea due to what exactly because there's way too much happening. Related PRs, but all of them seem to be integrated in 1.39.4 already so you're probably not hitting anything that's fixed already, but rather some new bug:

- https://github.com/emscripten-core/emscripten/pull/9654
- https://github.com/emscripten-core/emscripten/issues/9653
- https://github.com/emscripten-core/emscripten/issues/9733
- https://github.com/emscripten-core/emscripten/pull/9742

The `emar` script isn't too large on its own tho, so finding the root cause might not be too difficult.  Additionally it seems to be [printing some debug statements](https://github.com/emscripten-core/emscripten/blob/82c563cd5bfc70b9b061adfb34cf6d5249ce772c/emar.py#L78) (I guess if you pass `-s DEBUG=1` to it *somehow*), maybe that could point to something?

Is it happening with just this file or other files as well? This one is compiled into a CMake `OBJECT` library and then added to both `EmscriptenApplication` and `Sdl2Application`. So maybe that's what confuses it -- do you have enabled both applications? What if you explicitly build them in a particular order, can you reproduce it?

```sh
ninja MagnumEmscriptenApplication
ninja MagnumSdl2Application
```

**Comment by celentes** [comment]
It's happening with just this file, and always with that particular hash. I am building both Sdl2 and Emscripten applications, correct.
Some further digging - I couldn't reproduce it in single threaded make for the last 3 hours, but it gets reproduced fairly quickly in multithreaded. I just seen that:
```
[ 89%] Linking CXX static library ../../../Release/lib/MagnumSdl2Application.bc
[ 90%] Linking CXX static library ../../../Release/lib/MagnumEmscriptenApplication.bc
/emsdk_portable/clang/tag-e1.39.4/build_tag-e1.39.4_64/bin/llvm-ar: /buildroot/magnum/build/src/Magnum/Platform/CMakeFiles/MagnumPlatformObjects.dir/Implementation/DpiScaling_fe5a6db6.cpp.o: No such file or directory.
```
So it's plausible that whatever hash shenanigans they do are not thread safe. I'll dig a bit further to investigate. Thanks!

**Comment by mosra** [comment]
Wonderful, thanks! Good point, this seems to be a filesystem race.

**Comment by celentes** [comment]
Yeah, it is a filesystem race.
emar calculates a hash based on full file path, copies it with added hash, runs llvm-ar on it, then tries to delete it. So when two threads are running emar on the same file, one can delete the file before the other one has sent it off to llvm-ar.
I'll post an issue to emscripten

**Comment by celentes** [comment]
emscripten-core/emscripten#10152

**Comment by celentes** [comment]
fixed in emscripten/incoming

**Comment by mosra** [comment]
Wonderful, thanks for doing the hard work on this one 👍
