### ISSUE TITLE
basic cmake setup for examples

### ISSUE THREAD

**Issue by cruisercoder** [mosra/magnum#451]
For an all source build, I'm able to get the gray window from the getting started guide.  I'm not a cmake expert and  It's a bit unclear as to how to go from there to building the magnum-examples projects.

- do I check out magnum-examples at top level with magnum/corrade sub projects and add to the top level CMakeLists.txt?
- do I check out magnum/corrade subprojects within magnum-examples and connect from there?

**Comment by mosra** [comment]
Hi!

Either way should work. Note that by default only the Triangle example is enabled, set [various `WITH_*` options](https://doc.magnum.graphics/magnum/building-examples.html#building-examples-features) to enable the others. This is done because various examples depend on 3rd party libs (Box2D, Bullet, DART, Eigen, ...) and I don't want people to suffer through the full dependency hell implicitly :)

As a third and fourth option: 

- you can also clone the repo and `add_subdirectory(magnum)` etc. directly inside a particular example (for example in `src/arcball/CMakeLists.txt`) to build just that one and nothing else. 
- or reuse the scaffolding you have from the Getting Started Guide and copy the example sources into the `src/` directory.
