### ISSUE TITLE
cmake/vcpkg can't locate MagnumPlugins::AssimpImporter

### ISSUE THREAD

**Issue by TimYorke** [mosra/magnum#458]
After using vcpkg to install magnum and magnum-plugins[*] packages, the CMakeLists.txt line `find_package(MagnumPlugins REQUIRED AssimpImporter)` was failing.

I searched my vcpkg folder for Assimpimporter.lib and could only find them (rel and dbg) was in a sub-directory of the vcpkg/buildtrees folder. The exact location of the release version was _vcpkg\buildtrees\magnum-plugins\x64-windows-rel\Release\lib\magnum\importers\AssimpImporter.lib_

My workaround was to copy the _vcpkg\buildtrees\magnum-plugins\x64-windows-rel\Release\lib\magnum_ folder to _vcpkg\installed\x64-windows\lib\magnum_

**Comment by mosra** [comment]
Hi, in case of dynamic plugins (which is the default when you build a dynamic Vcpkg package), this is intentional -- the plugins are found and loaded at runtime and thus there's no need for any `find_package(MagnumPlugins ...)`. Vcpkg copies the relevant `*.dll`s into your executable directory and Magnum's plugin manager will look there at runtime. OTOH in case of a static build the plugins need to be explicitly found and linked, and in that case the `*.lib` files will be installed appropriately.

If I remember correctly, we had to explicitly ignore the `*.lib` files to avoid Vcpkg autolinking magic getting confused.

[Relevant docs about plugin usage here.](https://doc.magnum.graphics/magnum/plugins.html)
