### ISSUE TITLE
magnum version identification

### ISSUE THREAD

**Issue by Xeverous** [mosra/magnum#475]
It seems a bit strange to me, but I haven't found any explicit version in the public API. At best there is `Magnum::GL::Context::versionString()` but this returns OpenGL version, not the version of Magnum. Is there any official numbering? Or is the entire library still in "official beta" state and no explicit version numbering untill v1.0 is released? I noticed releases are labeled with dates, not increasing version numbers.

**Comment by mosra** [comment]
The versioning scheme is `year.month` and you can get year, month, Git commit hash prefix, the number of commits since last tag and a string version identification in [`<Magnum/version.h>`](https://github.com/mosra/magnum/blob/master/src/Magnum/version.h.cmake), which gets generated by CMake during build. If Magnum is not built from a Git clone, it'll contain just static information that was put there when the last tag happened. Similar is with other repos (corrade, plugins, extras, integration...).

This version header is quite recent (was added in March this year), so it's not really mentioned in the docs yet. Please note it's also explicitly *not* included transitively from other headers because it would trigger a rebuild/relink every time I do a Git commit, which isn't something I want.

**Comment by Xeverous** [comment]
Ok, that's all I need to know. Close this issue or do you want to keep it open (I see you added it a milestone)?

**Comment by mosra** [comment]
Great! :)
