### ISSUE TITLE
How to use something like "mainLoopIteration" in emscripten

### ISSUE THREAD

**Issue by werto87** [mosra/magnum#508]
Hi,

I am porting a client application with a gui to wasm.
The gui and networking shares one thread in a non blocking way by using coroutine-ts with boost asio/beast.

Currently there is a coroutine which contains a loop like this:
for (;;)
    {
       app.mainLoopIteration ();
      // give other coroutines a chance to run
    }

Is there some way to get similar behavior with emscripten application?

**Comment by mosra** [comment]
Due to the way browsers are designed, it's not possible for a web page to "take over" the main loop. You have to split all your work into small chunks done each frame, because if you block for too long, the browser kills the page as being unresponsive. (By the way, this is also why all Application classes in Magnum hide the main loop and give you just event functions -- because of the browser requirements.)

Not sure about the threading and boost dependencies either, you might have to port away from these or use something that's designed to work with Emscripten APIs (I have no experience with those, so I can't say if those are able to work there or not).

**Comment by werto87** [comment]
Thank you for the Information.

My understanding is:
My app only waits if all coroutines are suspended.
For example:
It draws a frame.
Then it gives control back to the scheduler.
The scheduler tries to execute another coroutine ready to start/continue.
The coroutine is resumed and runs until something will block then it gives back control to the scheduler using "co_await"  and so on.
I think its called "cooperative scheduling". If you are interested here is a good read about cooperative scheduling "https://medium.com/traveloka-engineering/cooperative-vs-preemptive-a-quest-to-maximize-concurrency-power-3b10c5a920fe".

So I think the concept should match with browsers.
I think  the problem is that the control is not in the hands of my app but in the browser.

Do you know if there is some function which is called by the browser when it wants to draw a new frame I think I can use it to execute a coroutine until it comes to the next "co_await" and control gets back to the coroutine schedular. Then I could some how give back control to the browser until it calls the new frame function again.

Sounds like a lot of fun. I am excited :)

**Comment by werto87** [comment]
I made a mini example. I added a coroutine to your imgui example. It prints every second hello world with out blocking.
Thank you for the great work! Integrationg coroutines was supper easy!!
example:
https://gist.github.com/werto87/a6351bc1835fc5e53f15943017d0a424

**Comment by unicomp21** [comment]
is there a way to use co_await when targetting webassembly?  @mosra

**Comment by werto87** [comment]
I use co_await in my client with wasm. For example in this file:   [https://github.com/werto87/game_01_client/blob/master/src/webservice/webservice.hxx](url). You can post your question in the project issue if you need help.

**Comment by unicomp21** [comment]
@werto87 thanks!!!
