### ISSUE TITLE
Restore Android and iOS builds on another CI service

### ISSUE THREAD

**Issue by mbrukman** [mosra/magnum#523]
There's still a [`.travis.yml`] symlink and a [`travis.yml`] config in the repository, but looks like Travis CI is no longer being used for this project:

* https://travis-ci.org/github/mosra/magnum says:

  > This repository was migrated and is now building on travis-ci.com

* the most recent build on https://travis-ci.com/github/mosra/magnum is from 7 months ago

Looks like this project is currently using AppVeyor and Circle CI instead, based on the other badges in the README.

Would it make sense to remove these files, and the Travis CI badge? Or if it's still in use, perhaps it makes sense to reactive the builds?

[`.travis.yml`]: https://github.com/mosra/magnum/blob/047c539a17b9b68d9bf6526b8974bf285956010f/.travis.yml
[`travis.yml`]: https://github.com/mosra/magnum/blob/047c539a17b9b68d9bf6526b8974bf285956010f/package/ci/travis.yml

**Comment by mosra** [comment]
Hi!

The issue is, that Travis said dot org will get shut down, gradually making it less and less usable, forcing me to migrate to dot com. But shortly after they cut off everyone from the service, demanding to either pay about $70/month or beg them for "free OSS credits" with extremely restrictive rules. I sent them several e-mails trying to negotiate a solution but they just ghosted me and nothing happened in the last 7 months. So I slowly [migrated what I could to CircleCI](https://magnum.graphics/build-status/).

What's left is an iOS and Android build that made use of device emulator on Travis CI to run unit tests. Those are nontrivial to port elsewhere (probably would need to use some paid service to test on real devices), and because I didn't find time to look into that yet, I left the relevant files and configs in the repo. This is a blocker for the next release, so I have to restore builds for these platforms one way or another.

**Comment by mosra** [comment]
Remaining Android builds got migrated in eaa95dd3321eebd651d6d5b4fa567575121010fb (now also including tests for GLES and Vulkan functionality on SwiftShader), iOS builds in d3a411ca726464000fbd6bcafb87b8a4816a467d, the now-obsolete Travis config files are removed as of 89e3c52dfaa5a198a6e3ea0ec9224e0295cd5ed2. Since a7b94a4b097294ce42de54132147118ee52fe3a6 there's also a new ARM64 build because both the Android and the iOS build are for an x86 {e,si}mulator now and thus there wouldn't be any build testing an ARM target otherwise.

Similar change is being done in other Magnum repositories.
