### ISSUE TITLE
 unable to find ....lib when I'm compiling to wasm

### ISSUE THREAD

**Issue by ActivePeter** [mosra/magnum#524]
![image](https://user-images.githubusercontent.com/8100696/124548872-ea0ed780-de60-11eb-9bb5-ad9ede81beb6.png)

"cmake.configureSettings": {
      "CMAKE_MAKE_PROGRAM": "C:/Program Files/ninja-win/ninja"
  },
  "cmake.generator": "Ninja",

**Comment by mosra** [comment]
Hi,

um, I don't even know where to start... Looks like you're using Conan? And then Conan most probably supplies those Windows-specific flags? I'm not aware of anything in Magnum that would supply those four libs, the only place is [in FindSDL2.cmake](https://github.com/mosra/magnum/blob/dbec10dbee8cc3c2b560c6e7de9166c2b6d2f002/modules/FindSDL2.cmake#L259-L263) but there's a lot more of them, not just four, and those are included only if Windows is actually detected. So that place doesn't seem to be where they are coming from.

I need more information from you -- how are you actually building for Emscripten? What were the steps? Supplying a toolchain file? The one recommended in the documentation or some other one? How is Conan involved with this? Does Conan have even Emscripten support? Do Magnum Conan packages have Emscripten support? Etc.

Since quite some time passed since you opened this, I assume you've already moved on. If 
it's still relevant, please reply with more info.
