### ISSUE TITLE
ObjectData3D deprecation not in changelog

### ISSUE THREAD

**Issue by EhWhoAmI** [mosra/magnum#555]
618fbeccaaa9c863cd88925647dea749f1a42b9d deprecates `ObjectData3D.h`, and associated files, however, the alternatives to what is useable is not in the changelog.

**Comment by mosra** [comment]
Umm ... what do you mean? The changelog entry is *literally* the first changed file in the commit you linked to. Plus all deprecation compiler warnings and documentation of the deprecated APIs explicitly mentions that [`Trade::SceneData`](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1SceneData.html) is the alternative.

Yes, it's not a 1:1 mapping, and porting away from `ObjectData` isn't just a trivial rename. Instead of having thousands of tiny loose objects, the scene hierarchy is all packed in a single `SceneData` container, in a data-oriented way. Please read through the documentation of the class, it should be detailed enough to help you understand the new workflow.

As usual, the deprecated APIs will be kept around for at least one more year or for the next and the following release, whichever takes longer. Which means that you're not forced to port ASAP, there already are certain other projects that keep using the deprecated APIs until they settle down and find time to do the port. You can do the same. To silence compiler complaints, you can wrap the deprecated calls in [`CORRADE_IGNORE_DEPRECATED_PUSH` and `_POP`](https://doc.magnum.graphics/corrade/Macros_8h.html#a3d9823862d0498c5a6cfe2dbc39f47c5) macros.
