### ISSUE TITLE
{Qt} Wrapped framebuffer vs. DefaultFramebuffer mapForRead()

### ISSUE THREAD

**Issue by asmaloney** [mosra/magnum#643]
I'm wrapping Qt's framebuffer as outlined in the bootstrap example and I'm trying to get the [mouse interaction example](https://magnum.graphics/showcase/mouseinteraction/) working using Magnum inside a QOpenGLWidget.

In the interaction example's `depthAt()`, it uses the default framebuffer like this:

```cpp
GL::defaultFramebuffer.mapForRead( GL::DefaultFramebuffer::ReadAttachment::Front );
```

`DefaultFramebuffer` takes a `ReadAttachment` as an argument to mapForRead():
```cpp
DefaultFramebuffer& DefaultFramebuffer::mapForRead(const ReadAttachment attachment)
```

The `FrameBuffer` class, however, takes a `ColorAttachment` instead:

```cpp
Framebuffer& Framebuffer::mapForRead(const ColorAttachment attachment)
```

How do I use a `ReadAttachment` with the `FrameBuffer` class? Or is there another way to fix this?

Thank you!

(I'm brand-new to magnum so still feeling my way around... maybe I'm missing something obvious?)

**Comment by mosra** [comment]
In the default GL framebuffer, to support double buffering, there's a concept of the front and back buffer. And (IIRC, it's been a while since I knew all the particulars for this example), reading from the front buffer ensures the currently written depth value is being read, not some previous one.

With a custom framebuffer there's no such thing as a front and back buffer because the custom framebuffer isn't directly used for presenting to a window. So if you read from it you'll always get the last written depth value. On the other hand, custom framebuffers support multiple color attachments (for deferred rendering, e.g., or for writing an object ID buffer in the [object picking example](https://magnum.graphics/showcase/picking/)), which is what the `ColorAttachment` allows to switch among. But you're reading a depth value, for which there's always just one buffer (and which is implicitly picked when calling `read()` with a depth pixel format, yes, GL is weird), so you shouldn't need to call `mapForRead()` at all.

Hope I didn't make it even more confusing by this explanation attempt :D

**Comment by asmaloney** [comment]
Thanks for the lightning-fast response Vladimír!

I think that makes sense. I will be trying to add in object picking after I get the camera moving the way I want it to.

I will continue with my experiments...

**Comment by asmaloney** [comment]
In case anyone ends up here trying to do the same thing (get the [mouse interaction example](https://magnum.graphics/showcase/mouseinteraction/) working using Magnum inside a [QOpenGLWidget](https://doc.qt.io/qt-6/qopenglwidget.html)), there are two things which tripped me up.

1) Related to the above, I needed to pass Qt's framebuffer to `depthAt()` by wrapping it like this:

```cpp
// Use framebuffer provided by Qt
const auto cRange = Magnum::Range2Di{ {}, { width(), height() } };
auto qtFramebuffer = Magnum::GL::Framebuffer::wrap( defaultFramebufferObject(), cRange );
```

So each of my mouse handling functions on my QOpenGLWodget look like this (calling into a private class to handle the magnum code):
```cpp
void mglWidget::mouseMoveEvent( QMouseEvent *inEvent )
{
   makeCurrent();

   // Use framebuffer provided by Qt
   const auto cRange = Magnum::Range2Di{ {}, { width(), height() } };
   auto qtFramebuffer = Magnum::GL::Framebuffer::wrap( defaultFramebufferObject(), cRange );

   bool changed = mPrivate->mouseMove( qtFramebuffer, inEvent );

   if ( changed )
   {
      update();
   }

   inEvent->accept();
}
```

2) You need to ensure multisampling is disabled on your`QSurfaceFormat` (it is off by default).

My scene was working in a test application, but when I dropped it into my main application it stopped working. I tracked it down to:
```cpp
format.setSamples( 8 );
```

Once I removed that from my main application the camera control worked.

**Comment by mosra** [comment]
The way to make this work with multisampling would be to add a non-multisampled depth-only framebuffer, to which you'd blit a small area around the cursor in order to resolve the samples, and then read from there. 

I'm doing something similar for the WebGL demo, which has multisampling enabled. (It's in the `ports` branch, but there's additional WebGL-specific nastiness in order to be able to read the depth back, so it's not really nice to read: https://github.com/mosra/magnum-examples/blob/ports/src/mouseinteraction/MouseInteractionExample.cpp)

**Comment by asmaloney** [comment]
Thanks for the pointer Vladimír. I'm _slowly_ starting to understand/remember some of this lower-level stuff - haven't looked at a framebuffer in over a decade 😄
