### ISSUE TITLE
Scene Viewer Example Failing on build

### ISSUE THREAD

**Issue by minoumao** [mosra/magnum#655]
We were trying to build the monkey scene viewer on our personal machine (me and 4 other people) from the monkey head viewer. However, when we run the scene we get the issue where all the threads will return 1. 

I dug and found out that for some reason, the command in the following:

    args.addArgument("file").setHelp("file", "file to load")
        .addOption("importer", "AnySceneImporter")
            .setHelp("importer", "importer plugin to use")
        .addSkippedPrefix("magnum", "engine-specific options")
        .setGlobalHelp("Displays a 3D scene file provided on command line.")
        .parse(arguments.argc, arguments.argv);
        
 the parse(arguments.argc, arguments.arg) is returning exit code of -1 because it fails to get an "end of line" command. We tried to figure out if it is an issue with our cmake, but because cmake compiles properly, we are unsure on what to do. 
 
 Tested and replicated this bug using the following:
 1) get a base.zip magnum file
 2) set up project following tutorial for monkey
 3) attempt to run the project and get the thread issue.
 
 Issue has been replicated on 5 different computers. Is this a cmake issue on our end (which is possible) or is this an bug?
 
 We want to make it so we can load a textured file in :(

I can provide files and the cmake if need be. The code is just the viewerexample.cpp and we are using the default blender monkey.

**Comment by mosra** [comment]
Hello -- I'm not sure what exactly you mean by an "end of line command", but the example expects a path to the model to view, in a format that the library is able to understand. If you don't pass any file, it'll say so in the standard output and exit; if you pass a file that it cannot open, it'll print a message and exit as well.

Thus, something like this:

```
./magnum-viewer path/to/scene.glb
```

If you're on Windows and don't see any terminal output, remove the `WIN32` part from the `add_executable()` command in the CMakeLists.

**Comment by minoumao** [comment]
Ill have my guys test it out!

**Comment by mosra** [comment]
This isn't related to CMake, it's how you invoke the actual executable once it's built. So, either in a terminal / console, or by specifying arguments when running the executable from an IDE. 

I don't know what system you're on or what IDE you use, so I unfortunately can only give you such a generic answer.

**Comment by minoumao** [comment]
So what I am trying to do is follow along with the base magnum file layout with the following folder layout:
======
CMakeLists.txt
build
src
assets
SDL2-2.0.10
magnum-plugins
magnum
corrade
moduels
======
Inside src is the ViewerExample.cpp and a CmakeList.txt
Inside assets is a file called scene.glb, which is what I am trying to open up. 

I have the following command in the src/CMakeList.txt
install(FILES scene.glb 
DESTINATION install(FILES scene.glb DESTINATION ${PROJECT_SOURCE_DIR}/assets/)

When i try to run the viewerexample it says file is a null argument. The parse() command in viewerexample.cpp throws the error that the argument does not have an end of line.

**Comment by mosra** [comment]
The root cause of the problem you're experiencing is still the same -- the executable expects a file path to be passed to it, so if you'd run it like this in `cmd.exe`

```
magnum-viewer.exe C:/..../assets/scene.glb
```

or create a `*.bat` file with such contents, and then run that instead, or, if you're running from an IDE, specifying the executable arguments, [like explained for example in this video](https://www.youtube.com/watch?v=O5nJJwSXLCc), then it would work.

If it doesn't get that, it complains -- says `Missing command-line argument file` -- and exits. I'm not sure what you mean by "null argument" or "does not have an end of line", neither of that is printed in the error message.

> I can get the code to run just fine by hardcoding the path from my computer using "C:/..../assets/scene.glb" instead of args.value("file") and skipping the whole args.parse().

Yes, that's basically circumventing the whole argument parsing, and yes, that's a valid workaround I guess. But the point of the example was showing how to load a model without having to hardcode its path to the program itself. 

The [Utility::Arguments](https://doc.magnum.graphics/corrade/classCorrade_1_1Utility_1_1Arguments.html) class performs parsing of the `argc` and `argv` arguments of `main()`, sure you've heard of that at least once if you're using C++?

```cpp
int main(int argc, char** argv) { // <-- these are command line arguments
    ...
}
```

I'm sorry, but I don't know how else I could explain this concept.
