### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by ColinGilbert** [mosra/magnum#82]
Hi,

You have a really cool project! However, I am targeting iOS, but have not found any indication of built-in support while reading the source. I found a minimalistic, MIT-licensed framework that does cross-platform GLES3, which you might be interested in:

https://github.com/danginsburg/opengles3-book/tree/master/Common/Source

Happy (belated) new year!

**Comment by mosra** [comment]
Hi, thanks a lot!

The problem is that I personally don't have access to any iOS device (or even Mac). The Mac OS X support was donated by various great people and I'm just blindly applying changes to that code in the hope that I won't break it.

As far as I know, there's no simple way to develop (and test) for iOS anywhere else than on Mac OS. I don't even have Android device, but that system has at least some emulator running on Linux and Windows, which I can use for testing.

So, at the moment, the support needs someone who has some iOS device and is brave enough to write the platform glue code. It shouldn't be anything hard, as the code is cross-platform and the GLES support is already done. The only thing left to do to have minimal iOS support is (hopefully) writing `Platform::IosApplication` or something like that which wires event handling etc. through to the C++ code. Or, if SDL2 has builtin iOS support, port `Platform::Sdl2Application` to iOS too.

**Comment by mosra** [comment]
I need an iOS port, so I may do some initial progress during January.

**Comment by mosra** [comment]
Initial port completed in 08c8f5a6350468a1ac20408d69d654c2b7df54e2. The `ports` branch of magnum-examples also has quite a few examples ported.
