### ISSUE TITLE
Cannot build on Gentoo

### ISSUE THREAD

**Issue by ColinGilbert** [mosra/magnum#83]
Hi,

I have built and installed Corrade using its standard buildscripts, but upon trying to build Magnum, I receive the following error:

```
num/build/src/Magnum/Shaders/resource_MagnumShaders_RCS.cpp
/usr/local/bin/corrade-rc: error while loading shared libraries: libCorradeUtility.so.0: cannot open shared object file: No such file or directory
src/Magnum/Shaders/CMakeFiles/MagnumShaders.dir/build.make:75: recipe for target 'src/Magnum/Shaders/resource_MagnumShaders_RCS.cpp' failed
make[2]: *** [src/Magnum/Shaders/resource_MagnumShaders_RCS.cpp] Error 127
CMakeFiles/Makefile2:849: recipe for target 'src/Magnum/Shaders/CMakeFiles/MagnumShaders.dir/all' failed
make[1]: *** [src/Magnum/Shaders/CMakeFiles/MagnumShaders.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

```
Any advice?

**Comment by mosra** [comment]
Hi,

I don't really know how Gentoo ebuilds work, but from the output it seems that it is not able to find the library in `/usr/local/lib` (because that directory is not in the library path on most systems). I assume that `/usr/local/lib/libCorradeUtility.so.0` exists.

Looking at the Corrade buildscript, it seems that the `-DCMAKE_INSTALL_PREFIX="${EPREFIX}/usr"` argument was somehow skipped and so the CMake default `/usr/local` prefix was used instead of `/usr`. 

in the [corrade-999.ebuild](https://github.com/mosra/corrade/blob/9ad6259bc3757865aae1fe0e64221f4641ce9190/package/gentoo/dev-libs/corrade/corrade-9999.ebuild#L25) file there is something fishy with the `\` line continuation characters, can you try to remove all of them like in the following snippet to see if it gets installed into proper location?

```bash
	...
	local mycmakeargs=(
		-DCMAKE_INSTALL_PREFIX="${EPREFIX}/usr"
		-DCMAKE_BUILD_TYPE=Debug
		-DBUILD_TESTS=TRUE
		-DWITH_FIND_MODULE=TRUE
	)
	...
```

If that won't help, does CMake print any error/warning when building Corrade?

**Comment by ColinGilbert** [comment]
Just built from Github repo tonight.

**Comment by mosra** [comment]
Glad to know it's fixed :)
